/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2024-11-11 13:15:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ohora;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1730336729000L));
    _jspx_dependants.put("jar:file:/C:/Users/USER/Desktop/OhoraTest/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/projectOhora/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>ohora 오호라 공식몰</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"projectOhora/resources/cdn-main/about.css\">\r\n");
      out.write("<link rel=\"shortcut icon\"\r\n");
      out.write("	href=\"https://www.ohora.kr/web/upload/favicon_20190801113230.ico\" />\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta name=\"google\" content=\"notranslate\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.rawgit.com/mfd/09b70eb47474836f25a21660282ce0fd/raw/e06a670afcb2b861ed2ac4a1ef752d062ef6b46b/Gilroy.css\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://gists.rawgit.com/mfd/09b70eb47474836f25a21660282ce0fd/raw/e06a670afcb2b861ed2ac4a1ef752d062ef6b46b/Gilroy.css\">\r\n");
      out.write("<!-- 구글폰트 -->\r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"http://localhost/jspPro/resources/cdn-main/example.css\"> 강사님이 주신 링크 이고-->\r\n");
      out.write("<!-- <script src=\"http://localhost/jspPro/resources/cdn-main/example.js\"></script> -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"https://www.ohora.kr/ind-script/optimizer.php?filename=nY1BCkIxDAX3pVvPERU9gTcQPEBa87X8NClpCnp7xZUbQbp9vJmBu1aC3d6gmd4MKxh1HZYJcu-wmIpD1lpV4nvYwD9_yqErDy8qIeljEhzus1HGJ9kc6piYJlFtgYtQSCjys88lwaU0zCucv30nZJIrGhziMW5hYfRW8vrRvAA&type=css&k=3572cbbdf8913438f1d2bd7f51c552f63984d500&t=1726130154\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"https://www.ohora.kr/ind-script/optimizer_user.php?filename=rdDLbcMwDADQu51r56BtBAl67giZQJYZi6koqqLkwp2-aoNMIB9Jgo8fcMIIaPuimBTESTLTML5DLLMn27vMHnTBfkGlNYB-UhjPZ5iTCYtmSTs8vgqm_XQv3kez4smqvkE7Ow3TOFyHS5NHG9R24I9SUb7ZJN7PJjWZf6B-U8R0xGq09VaYJTRh3uxSMsxGyf6zaLsaYFcL2H4uy1I8vqZw8ZnUSbw5ipHCerBvJWyVIAnRHvuVZ6JTR_fcSczE9PN8zy8&type=css&k=d7b0e35340531480ace045afa6396e34bdddf114&t=1704157192&user=T\" />\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.rawgit.com/mfd/09b70eb47474836f25a21660282ce0fd/raw/e06a670afcb2b861ed2ac4a1ef752d062ef6b46b/Gilroy.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"wrap\" style=\"padding-top: 0px !important;\">\r\n");
      out.write("	<div id=\"container\">\r\n");
      out.write("		<div id=\"contents\">\r\n");
      out.write("			<div id=\"brandstory\" class=\"fullpage-wrapper\"\r\n");
      out.write("				style=\"height: 100%; position: relative; touch-action: none; transform: translate3d(0px, 0px, 0px); transition: 700ms;\">\r\n");
      out.write("				<div class=\"vision section col90 fp-section fp-table\"\r\n");
      out.write("					style=\"height: 911px;\">\r\n");
      out.write("					<div class=\"fp-tableCell\" style=\"height: 911px;\">\r\n");
      out.write("						<div class=\"big_title\">\r\n");
      out.write("							<h2>\r\n");
      out.write("								<a href=\"https://www.ohora.kr/index.html\">\r\n");
      out.write("								<img src=\"https://www.ohora.kr/web/brandstory/ohora_BI_logotype_white.png\"\r\n");
      out.write("									alt=\"ohora\" style=\"width: 119px;\"></a><span class=\"logo\"></span>\r\n");
      out.write("							</h2>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"inner col2\" style=\"white-space: nowrap;\">\r\n");
      out.write("							<img class=\"title trans1\" src=\"https://www.ohora.kr/web/brandstory/ohora_BI_logotype_white.png\"\r\n");
      out.write("								alt=\"ohora\" style=\"width: 340px;\"> &nbsp;\r\n");
      out.write("							<div class=\"left_area area trans1 trans_d1\">\r\n");
      out.write("								<p>\r\n");
      out.write("									beyond<br>extraordinary\r\n");
      out.write("									</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<span class=\"scroll\"></span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"story section col90 fp-section fp-table\"\r\n");
      out.write("					style=\"height: 911px;\">\r\n");
      out.write("					<div class=\"fp-tableCell\" style=\"height: 911px;\">\r\n");
      out.write("						<div class=\"inner col2\">\r\n");
      out.write("							<p class=\"title trans1\"\r\n");
      out.write("								style=\"color: #e4d2ac; float: left; line-height: 100px; font-weight: 900;\">\r\n");
      out.write("								we innovate,<br>we push our\r\n");
      out.write("							</p>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"inner col2\" style=\"text-align: right !important;\">\r\n");
      out.write("							<p class=\"title trans1\"\r\n");
      out.write("								style=\"color: #e4d2ac; padding-top: 400px; font-weight: 900;\">boundaries</p>\r\n");
      out.write("							<div class=\"left_area area trans1 trans_d1\">\r\n");
      out.write("								<p\r\n");
      out.write("									style=\"color: #e4d2ac; font-family: 'Noto Sans KR', sans-serif !important; font-weight: 500 !important;\">\r\n");
      out.write("									우리는 당연하지 않은것들의 가능성을 믿습니다.<br> 오호라는 새로운 것에 도전하여 혁신적이고<br>\r\n");
      out.write("									의미있는 제품을 선보이고 있습니다.\r\n");
      out.write("								</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<span class=\"scroll\"></span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"philosophy section col90 fp-section fp-table\"\r\n");
      out.write("					style=\"height: 911px;\">\r\n");
      out.write("					<div class=\"fp-tableCell\" style=\"height: 911px;\">\r\n");
      out.write("						<div class=\"inner col2\"\r\n");
      out.write("							style=\"max-width: 1920px; padding: 0 150px;\">\r\n");
      out.write("							<p class=\"title trans1\" style=\"color: #000;\">\r\n");
      out.write("								we constantly<br>deliver<br>the extraordinary\r\n");
      out.write("							</p>\r\n");
      out.write("							<div class=\"area trans1 trans_d1\" style=\"display: block;\">\r\n");
      out.write("								<p\r\n");
      out.write("									style=\"font-family: 'Noto Sans KR', sans-serif !important; font-weight: 500 !important; color: #000;\">\r\n");
      out.write("									우리는 가장 나 다운 것이 가장 독보적인 것이라고 믿습니다.<br> 오호라는 시간과 공간의 제약없이 가장\r\n");
      out.write("									나다울 수 있는<br> 디자인과 네일 경험을 선사하고 있습니다.\r\n");
      out.write("								</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"material section col90 fp-section fp-table\" style=\"height: 911px;\">\r\n");
      out.write("					<div class=\"fp-tableCell\" style=\"height: 911px;\">\r\n");
      out.write("						<div class=\"inner\" style=\"max-width: 1920px; padding: 0 350px;\">\r\n");
      out.write("							<div class=\"area\">\r\n");
      out.write("								<p class=\"title trans1\"\r\n");
      out.write("									style=\"color: #e4d2ac; white-space: nowrap;\">\r\n");
      out.write("									we believe<br>in connecting<br>meaningfully<br>with\r\n");
      out.write("									each other\r\n");
      out.write("								</p>\r\n");
      out.write("								<p class=\"trans1 trans_d1\"\r\n");
      out.write("									style=\"color: #e4d2ac; padding-left: 55% !important; font-family: 'Noto Sans KR', sans-serif !important; font-weight: 500 !important; white-space: nowrap;\">\r\n");
      out.write("									우리는 사랑하는 사람들과 함께하는 시간의 가치를 믿습니다.<br> 오호라는 세상을 조금 더 즐겁고 의미\r\n");
      out.write("									있는 곳을 변화시키는<br> 네일 문화를 만들어 가고 있습니다.\r\n");
      out.write("								</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"recruit section col90 fp-section fp-table\"\r\n");
      out.write("					style=\"height: 911px;\">\r\n");
      out.write("					<div class=\"fp-tableCell\" style=\"height: 911px;\">\r\n");
      out.write("						<div class=\"big_title\">\r\n");
      out.write("							<h2>\r\n");
      out.write("								<span class=\"logo\"><a\r\n");
      out.write("									href=\"https://www.ohora.kr/index.html\"><img\r\n");
      out.write("										src=\"https://www.ohora.kr/web/brandstory/ohora_BI_logotype_white.png\"\r\n");
      out.write("										alt=\"andar\" style=\"width: 119px;\"></a></span>\r\n");
      out.write("							</h2>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"inner\" style=\"max-width: 1920px; padding: 0 150px;\">\r\n");
      out.write("							<div class=\"area\">\r\n");
      out.write("								<p class=\"title trans1\"\r\n");
      out.write("									style=\"color: #e4d2ac; white-space: nowrap;\">\r\n");
      out.write("									connect with<br>yourself,<br>connect with others,<br>who\r\n");
      out.write("									you love\r\n");
      out.write("								</p>\r\n");
      out.write("								<p class=\"trans1 trans_d1\"\r\n");
      out.write("									style=\"color: #e4d2ac; padding-left: 0 !Important; font-family: 'Noto Sans KR', sans-serif !important; font-weight: 500 !important; white-space: nowrap;\">\r\n");
      out.write("									나를 위한 시간을 갖고 내가 사랑하는 사람들과 시간을 함께하는 오호라</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"fp-nav\" class=\"fp-show-active right\" style=\"margin-top: -65.5px;\">\r\n");
      out.write("	<ul>\r\n");
      out.write("		<li><a href=\"#\" class=\"active\"><span></span></a></li>\r\n");
      out.write("		<li><a href=\"#\" class=\"\"><span></span></a></li>\r\n");
      out.write("		<li><a href=\"#\" class=\"\"><span></span></a></li>\r\n");
      out.write("		<li><a href=\"#\" class=\"\"><span></span></a></li>\r\n");
      out.write("		<li><a href=\"#\" class=\"\"><span></span></a></li></ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("//시작시 큰 로고 움직이기\r\n");
      out.write("$('window').ready(function () {\r\n");
      out.write("	$('.col90').eq(0).addClass(\"active fp-completely\");\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("// 클릭 시 선택 유지\r\n");
      out.write("$('a').on(\"click\", function () {\r\n");
      out.write("    $('a').removeClass(\"active\"); \r\n");
      out.write("    $(this).addClass(\"active\"); \r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//a태그 클릭시 스크롤로 이동하기\r\n");
      out.write("$(\"a\").on(\"click\", function (e) {\r\n");
      out.write("    e.preventDefault();\r\n");
      out.write("\r\n");
      out.write("    const index = $(\"a\").index(this); // 2부터 시작\r\n");
      out.write("   \r\n");
      out.write("	if(index >= 2){\r\n");
      out.write("		const st = 911*(index-2);\r\n");
      out.write("    	$(\"html, body\").animate({ scrollTop: st }, 500);\r\n");
      out.write("	}\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("window.addEventListener(\r\n");
      out.write("		\"wheel\", function (e) {\r\n");
      out.write("			e.preventDefault();\r\n");
      out.write("\r\n");
      out.write("		    const delta = e.deltaY; //휠 방향을 감지\r\n");
      out.write("			const point = $(window).scrollTop();\r\n");
      out.write("		    \r\n");
      out.write("			if(delta < 0){	//마우스 휠을 올렸을때\r\n");
      out.write("		    	$(\"html, body\").stop(true).animate({ scrollTop: point-911 }, 500);\r\n");
      out.write("				}else if (delta > 0) { //마우스 휠을 내렸을때\r\n");
      out.write("		    	$(\"html, body\").stop(true).animate({ scrollTop: point+911 }, 500);\r\n");
      out.write("				}\r\n");
      out.write("		}\r\n");
      out.write("		, { passive: false }\r\n");
      out.write("		);\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("$(window).on(\"scroll\", function () {\r\n");
      out.write("	$('a').removeClass(\"active\"); \r\n");
      out.write("	$('.col90').removeClass(\"active fp-completely\");\r\n");
      out.write("    const st = $(window).scrollTop();\r\n");
      out.write("	//console.log(st);\r\n");
      out.write("	if(st < 911){\r\n");
      out.write("	$(\"a\").eq(2).addClass(\"active\");\r\n");
      out.write("	$('.col90').eq(0).addClass(\"active fp-completely\");\r\n");
      out.write("	}else if(st >= 911 && st < 1822){\r\n");
      out.write("	$(\"a\").eq(3).addClass(\"active\");\r\n");
      out.write("	$('.col90').eq(1).addClass(\"active fp-completely\");\r\n");
      out.write("	}else if (st >= 1822 && st < 2733) {\r\n");
      out.write("	$(\"a\").eq(4).addClass(\"active\");\r\n");
      out.write("	$('.col90').eq(2).addClass(\"active fp-completely\");\r\n");
      out.write("	}else if (st >= 2733 && st < 3644) {\r\n");
      out.write("	$(\"a\").eq(5).addClass(\"active\");\r\n");
      out.write("	$('.col90').eq(3).addClass(\"active fp-completely\");\r\n");
      out.write("	}else if (st >= 3644) {\r\n");
      out.write("	$(\"a\").eq(6).addClass(\"active\");\r\n");
      out.write("	$('.col90').eq(4).addClass(\"active fp-completely\");\r\n");
      out.write("	}\r\n");
      out.write("})\r\n");
      out.write("		\r\n");
      out.write("$(document).on(\"keydown\", function(e) {\r\n");
      out.write("    const st = $(window).scrollTop();\r\n");
      out.write("\r\n");
      out.write("    if (e.key === \"ArrowUp\" || e.keyCode === 38 || e.keyCode === 33) { // 위쪽 방향키\r\n");
      out.write("        $(\"html, body\").stop(true).animate({ scrollTop: st - 911 }, 500);\r\n");
      out.write("        e.preventDefault();\r\n");
      out.write("    } else if (e.key === \"ArrowDown\" || e.keyCode === 40 || e.keyCode === 34) { // 아래쪽 방향키\r\n");
      out.write("        $(\"html, body\").stop(true).animate({ scrollTop: st + 911 }, 500);\r\n");
      out.write("        e.preventDefault(); \r\n");
      out.write("    }\r\n");
      out.write("});		\r\n");
      out.write("		\r\n");
      out.write("</script>\r\n");
      out.write(" \r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
