/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2024-11-09 12:24:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ohora;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class howto_005fdetail04_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/ohora/header.jsp", Long.valueOf(1731149610173L));
    _jspx_dependants.put("/ohora/footer.jsp", Long.valueOf(1731141752591L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1730336729000L));
    _jspx_dependants.put("jar:file:/C:/Users/USER/Desktop/OhoraTest/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/projectOhora/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>스트링리무버 사용편 how to - ohora</title>\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"../resources/images/favicon.ico\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/projectOhora/resources/cdn-main/howto_detail.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("<meta name=\"google\" content=\"notranslate\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<style>\r\n");
      out.write(".xans-board-readpackage-8 .SP_cm_btn.SP_btn_gray_bd {\r\n");
      out.write("	display: inline-block !important;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");

	Integer userId = (Integer) session.getAttribute("userId");
	Integer productCount = (Integer) session.getAttribute("productCount");
	
	// 값 확인
	System.out.println("header userId : " + userId);
	System.out.println("header productCount : " + productCount);
	
	String contextPath = request.getContextPath();

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>오호라</title>\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"http://localhost/jspPro/images/SiSt.ico\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta name=\"google\" content=\"notranslate\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/projectOhora/resources/cdn-main/header.css\">\r\n");
      out.write("<script src=\"http://localhost/jspPro/resources/cdn-main/example.js\"></script>\r\n");
      out.write("  <link\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      type=\"text/css\"\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css\"\r\n");
      out.write("    />\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write(" span.material-symbols-outlined{\r\n");
      out.write("    vertical-align: text-bottom;\r\n");
      out.write(" }  \r\n");
      out.write("</style>\r\n");
      out.write("  \r\n");
      out.write("</head>\r\n");
      out.write("<div class=\"SP_topBanner\" style=\"display: block\">\r\n");
      out.write("      <div class=\"SP_layoutMin\">\r\n");
      out.write("        <div class=\"SP_topBn_inr\"></div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"xans-element- xans-layout xans-layout-statelogoff\">\r\n");
      out.write("          <div\r\n");
      out.write("            class=\"slide_banner_top slick-initialized slick-slider\"\r\n");
      out.write("            id=\"sltop_ban\"\r\n");
      out.write("          >\r\n");
      out.write("            <div class=\"slick-list draggable\">\r\n");
      out.write("              <div\r\n");
      out.write("                class=\"slick-track\"\r\n");
      out.write("                style=\"\r\n");
      out.write("                  opacity: 1;\r\n");
      out.write("                  width: 1200px;\r\n");
      out.write("                  transform: translate3d(0px, 0px, 0px);\r\n");
      out.write("                \"\r\n");
      out.write("              >\r\n");
      out.write("                <div\r\n");
      out.write("                  class=\"slick-slide slick-current slick-active\"\r\n");
      out.write("                  data-slick-index=\"0\"\r\n");
      out.write("                  aria-hidden=\"false\"\r\n");
      out.write("                  style=\"width: 1200px\"\r\n");
      out.write("                  tabindex=\"0\"\r\n");
      out.write("                >\r\n");
      out.write("                  <a\r\n");
      out.write("                    href=\"/event/event6.html\"\r\n");
      out.write("                    tabindex=\"0\"\r\n");
      out.write("                    style=\"display: block\"\r\n");
      out.write("                    ><img\r\n");
      out.write("                      src=\"https://ohora.kr/optimize/images/pc/common/PC_header_lamp2.webp\"\r\n");
      out.write("                      style=\"width: 100%; display: block\"\r\n");
      out.write("                  /></a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- 회원 -->\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"fix_position\" class=\"modify ham_modify\">\r\n");
      out.write("      <div id=\"SMS_fixed_wrap\" class=\"SMS_fixed_wrap\">\r\n");
      out.write("        <div class=\"SP_top_wrap\">\r\n");
      out.write("          <div class=\"layout_Top\">\r\n");
      out.write("            <div\r\n");
      out.write("              class=\"xans-element- xans-layout xans-layout-statelogoff SP_gnb_inr\"\r\n");
      out.write("            >\r\n");
      out.write("            <!-- 갱신함 / 경로는 아직 안넣음 -->\r\n");
      out.write("            ");

            	if ( userId == null ) {
            
      out.write("<a href=\"");
      out.print( contextPath );
      out.write("/ohora.do?join=signup\"><span class=\"title\">회원가입</span></a>|\r\n");
      out.write("	              <a href=\"");
      out.print( contextPath );
      out.write("/ohora.do?login=gologin\" class=\"log\"><span class=\"title\">로그인</span></a>\r\n");
      out.write("            ");
		
            	} else if  ( userId == 1001 ) {
            
      out.write("<a href=\"");
      out.print( contextPath );
      out.write("/admin/product.do\"><span class=\"title\">관리자페이지</span></a>|\r\n");
      out.write("	             <a href=\"");
      out.print(contextPath );
      out.write("/logout/logout.do\" class=\"log\"><span class=\"title\">로그아웃</span></a>\r\n");
      out.write("            ");

            	} else {
            
      out.write("<a href=\"");
      out.print( contextPath );
      out.write("/mypage/mypage.do?user_id=userId\"><span class=\"title\">마이페이지</span></a>|\r\n");
      out.write("	             <a href=\"");
      out.print(contextPath );
      out.write("/logout/logout.do\" class=\"log\"><span class=\"title\">로그아웃</span></a>\r\n");
      out.write("              ");

            	} 
            
      out.write("</div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"SMS_fixed_inner\">\r\n");
      out.write("          <div class=\"xans-element- xans-layout xans-layout-logotop fixed_logo\">\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"");
      out.print( contextPath );
      out.write("/product/main.do\"\r\n");
      out.write("              style=\"display: block; text-align: center; margin-top: 30px\"\r\n");
      out.write("            >\r\n");
      out.write("              <img\r\n");
      out.write("                src=\"https://ohora.kr/web/upload/logo/ohora_BI_logotype_w.png\"\r\n");
      out.write("                style=\"margin-bottom: 7px\"\r\n");
      out.write("              />\r\n");
      out.write("            </a>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!-- 헤더 주메뉴 -->\r\n");
      out.write("          <div class=\"gnb_menu_container\">\r\n");
      out.write("            <ul class=\"gnb_menu_wrap menu_1ul\">\r\n");
      out.write("              <li class=\"eng_font menu_1li submenu\">\r\n");
      out.write("                <a href=\"/projectOhora/product/list.do?sort=new\">new</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"eng_font menu_1li submenu\">\r\n");
      out.write("                <a href=\"/projectOhora/product/list.do?sort=sales\">best</a>\r\n");
      out.write("              </li>\r\n");
      out.write("\r\n");
      out.write("              <li class=\"eng_font\">\r\n");
      out.write("                <a href=\"/projectOhora/product/list.do\">product</a>\r\n");
      out.write("\r\n");
      out.write("                <!-- 마우스 오버 시 나오는 영역(product) -->\r\n");
      out.write("                <ul class=\"menu_2ul\">\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"/product/list.html?cate_no=160\"\r\n");
      out.write("                      ><span>네일</span></a\r\n");
      out.write("                    >\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"/product/list.html?cate_no=161\"\r\n");
      out.write("                      ><span>페디</span></a\r\n");
      out.write("                    >\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"/product/list.html?cate_no=470\"\r\n");
      out.write("                      ><span>커스텀</span></a\r\n");
      out.write("                    >\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"/product/list.html?cate_no=49\"\r\n");
      out.write("                      ><span>케어 &amp; 툴</span></a\r\n");
      out.write("                    >\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <!-- //마우스 오버 시 나오는 영역(product) -->\r\n");
      out.write("              </li>\r\n");
      out.write("\r\n");
      out.write("              <li class=\"eng_font menu_1li submenu\">\r\n");
      out.write("                <a href=\"/projectOhora/product/list.do?sort=outlet\">outlet</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"eng_font\"><a href=\"");
      out.print( contextPath );
      out.write("/ohora.do?event=event\">event</a></li>\r\n");
      out.write("              <li class=\"eng_font\">\r\n");
      out.write("                <a href=\"");
      out.print( contextPath );
      out.write("/ohora.do?howto=howto\">how to</a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- //헤더 주메뉴 -->\r\n");
      out.write("\r\n");
      out.write("          <div class=\"icon_wrap\">\r\n");
      out.write("            <div class=\"small_icon search_fixed_btn\"></div>\r\n");
      out.write("            <div\r\n");
      out.write("              class=\"xans-element- xans-layout xans-layout-orderbasketcount small_icon m_cart common_cart\"\r\n");
      out.write("            >\r\n");
      out.write("              <!-- 고정 값 0 을 어떻게 동적으로 바꾸는가 -->\r\n");
      out.write("              ");
      //  c:choose
      org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
      boolean _jspx_th_c_005fchoose_005f0_reused = false;
      try {
        _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fchoose_005f0.setParent(null);
        int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
        if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            //  c:when
            org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
            boolean _jspx_th_c_005fwhen_005f0_reused = false;
            try {
              _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
              _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
              // /ohora/header.jsp(182,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userId != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
              int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
              if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("<form action=\"");
                  out.print(contextPath );
                  out.write("/cart/useriscart.do\" method=\"post\" id=\"CartForm\">\r\n");
                  out.write("			            <a href=\"#\" id=\"goCart\">\r\n");
                  out.write("			                <b class=\"count EC-Layout-Basket-count\">");
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write("</b>\r\n");
                  out.write("			            </a>\r\n");
                  out.write("			        </form>\r\n");
                  out.write("			    ");
                  int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
              _jspx_th_c_005fwhen_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
            }
            //  c:otherwise
            org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
            boolean _jspx_th_c_005fotherwise_005f0_reused = false;
            try {
              _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
              _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
              int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
              if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("<form action=\"");
                  out.print(contextPath );
                  out.write("/cart/nousercart.do\" method=\"post\" id=\"CartForm\">\r\n");
                  out.write("			            <a href=\"#\" id=\"goCart\">\r\n");
                  out.write("			                <b class=\"count EC-Layout-Basket-count\">0</b>\r\n");
                  out.write("			            </a>\r\n");
                  out.write("			        </form>\r\n");
                  out.write("			    ");
                  int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
              _jspx_th_c_005fotherwise_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
            }
            int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
        _jspx_th_c_005fchoose_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
      }
      out.write("</div>\r\n");
      out.write("            <div class=\"small_icon m_menu\"><a class=\"SMS_menu\"></a></div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    <!-- 검색 -->\r\n");
      out.write("    <div class=\"hd_search_container\" style=\"overflow: hidden; display: none\">\r\n");
      out.write("      <div class=\"SP_search_wrap\">\r\n");
      out.write("        <div class=\"SP_utilListSearch_inner\">\r\n");
      out.write("          <form\r\n");
      out.write("            id=\"searchBarForm\"\r\n");
      out.write("            name=\"\"\r\n");
      out.write("            action=\"/product/search.html\"\r\n");
      out.write("            method=\"get\"\r\n");
      out.write("            target=\"_self\"\r\n");
      out.write("            enctype=\"multipart/form-data\"\r\n");
      out.write("          >\r\n");
      out.write("            <input id=\"banner_action\" name=\"banner_action\" value=\"\" type=\"hidden\" />\r\n");
      out.write("            <div class=\"xans-element- xans-layout xans-layout-searchheader\">\r\n");
      out.write("          \r\n");
      out.write("              <fieldset>\r\n");
      out.write("                <legend style=\"display: none\">검색</legend>\r\n");
      out.write("                <input\r\n");
      out.write("                  id=\"keyword\"\r\n");
      out.write("                  name=\"keyword\"\r\n");
      out.write("                  fw-filter=\"\"\r\n");
      out.write("                  fw-label=\"검색어\"\r\n");
      out.write("                  fw-msg=\"\"\r\n");
      out.write("                  class=\"inputTypeText\"\r\n");
      out.write("                  placeholder=\"\"\r\n");
      out.write("                  onkeyup=\"SEARCH_HASHTAG.getHashtag($(this)); \"\r\n");
      out.write("                  autocomplete=\"off\"\r\n");
      out.write("                  onmousedown=\"SEARCH_BANNER.clickSearchForm(this)\"\r\n");
      out.write("                  value=\"\"\r\n");
      out.write("                  type=\"text\"\r\n");
      out.write("                /><button\r\n");
      out.write("                  type=\"button\"\r\n");
      out.write("                  class=\"SP_srh_submit_btn\"\r\n");
      out.write("                  onclick=\"SEARCH_BANNER.submitSearchBanner(this); return false;\"\r\n");
      out.write("                >\r\n");
      out.write("                  <span class=\"SP_cm_icon SP_black_search_icon\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("              </fieldset>\r\n");
      out.write("            </div>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    \r\n");
      out.write("        <!--------------- 검색 키워드 --------------->\r\n");
      out.write("        <div class=\"SP_utilListKeyword_inner\">\r\n");
      out.write("          <ul>\r\n");
      out.write("            <li><a href=\"/projectOhora/product/list.do?sort=outlet\">#OUTLET 입장하기</a></li>\r\n");
      out.write("            <li><a href=\"/projectOhora/product/list.do\">#BEST 디자인 추천</a></li>\r\n");
      out.write("            <li><a href=\"a href=\"");
      out.print( contextPath );
      out.write("/ohora.do?event=event6\">#첫구매 젤램프 증정</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--------------- 검색 키워드 --------------->\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- 더보기 -->\r\n");
      out.write("    <div class=\"hd_cate_container\" style=\"overflow: hidden; display: none\">\r\n");
      out.write("      <div class=\"SP_category_wrap\" style=\"margin-top: 172px;\">\r\n");
      out.write("        <div class=\"inner\">\r\n");
      out.write("      \r\n");
      out.write("          <div class=\"cate_wrap first\">\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("            <div class=\"big_txt\">\r\n");
      out.write("              <a class=\"eng_font big_\" href=\"/projectOhora/product/list.do\">\r\n");
      out.write("                <span>new</span>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a class=\"\" href=\"/projectOhora/product/list.do\">\r\n");
      out.write("                <span></span>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a class=\"\" href=\"/projectOhora/product/list.do\">\r\n");
      out.write("                <span></span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"big_txt\">\r\n");
      out.write("              <a class=\"eng_font big_\" href=\"/projectOhora/product/list.do\">\r\n");
      out.write("                <span>best</span>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a href=\"/projectOhora/product/list.do\">\r\n");
      out.write("                <span>네일</span>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a href=\"/projectOhora/product/list.do\">\r\n");
      out.write("                <span>페디</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"cate_wrap first\">\r\n");
      out.write("            <div class=\"big_txt\">\r\n");
      out.write("              <a class=\"eng_font big_\" href=\"/product/list.html?cate_no=160\">\r\n");
      out.write("                <span>nail</span>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a class=\"\" href=\"/product/list.html?cate_no=435\">\r\n");
      out.write("                <span>젤스트립</span>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a class=\"\" href=\"/product/list.html?cate_no=436\">\r\n");
      out.write("                <span>젤네일팁</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"big_txt\">\r\n");
      out.write("              <a class=\"eng_font big_\" href=\"/projectOhora/product/list.do\">\r\n");
      out.write("                <span>pedi</span>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a class=\"\" href=\"/projectOhora/product/list.do\">\r\n");
      out.write("                <span>젤스트립</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"cate_wrap first\">\r\n");
      out.write("            <div class=\"big_txt\">\r\n");
      out.write("              <a class=\"eng_font big_\" href=\"/projectOhora/product/list.do\">\r\n");
      out.write("                <span>outlet</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"big_txt\">\r\n");
      out.write("              <span></span>\r\n");
      out.write("\r\n");
      out.write("              <span></span>\r\n");
      out.write("\r\n");
      out.write("              <span></span>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"big_txt\">\r\n");
      out.write("              <a class=\"eng_font big_\" href=\"/projectOhora/product/list.do\">\r\n");
      out.write("                <span>custom</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"big_txt\">\r\n");
      out.write("              <a class=\"eng_font big_\" href=\"/projectOhora/product/list.do\">\r\n");
      out.write("                <span>care &amp; tool</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!--------- 첫번째 줄 메뉴(신제품 출시 관련 수정 영역) --------->\r\n");
      out.write("          <style>\r\n");
      out.write("          \r\n");
      out.write("          </style>\r\n");
      out.write("\r\n");
      out.write("          <!------- 두번째 줄 메뉴 ------>\r\n");
      out.write("          <div class=\"cate_wrap second\">\r\n");
      out.write("  \r\n");
      out.write("            <div class=\"big_txt\" style=\"margin-left: 35px; margin-bottom: 42px;\">\r\n");
      out.write("              <a class=\"big_ eng_font\" href=\"/projectOhora/ohora/event_index.jsp\">\r\n");
      out.write("                <span>event</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"big_txt\" style=\"margin-left: 35px;  margin-bottom: 42px;\">\r\n");
      out.write("              <a\r\n");
      out.write("                class=\"big_ eng_font\"\r\n");
      out.write("                href=\"/projectOhora/ohora/oho_review.jsp\"\r\n");
      out.write("              >\r\n");
      out.write("                <span>review</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"big_txt\" style=\"margin-left: 35px;\">\r\n");
      out.write("              <a class=\"big_ eng_font\" href=\"#empty\">\r\n");
      out.write("                <span style=\"margin-top: 10px;\">brand</span>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a class=\"\" href=\"/projectOhora/ohora/ohora_Fend_brand4.jsp\">\r\n");
      out.write("                <span>about</span>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a class=\"\" href=\"/projectOhora/ohora/membership.jsp\">\r\n");
      out.write("                <span>membership</span>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a class=\"\" href=\"/projectOhora/ohora/magazine.jsp\">\r\n");
      out.write("                <span>magazine</span>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a class=\"\" href=\"#empty\">\r\n");
      out.write("                <span>collaboration</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!------ 두번째 줄 메뉴 ------>\r\n");
      out.write("          <!------ 세번째 줄 메뉴 ------>\r\n");
      out.write("          <div class=\"cate_wrap crew\">\r\n");
      out.write("            <!--오호라 크루 추천-->\r\n");
      out.write("            <div\r\n");
      out.write("              class=\"common_reco_section recommend_crew swiper-container swiper-container-initialized swiper-container-horizontal load-complete\"\r\n");
      out.write("            >\r\n");
      out.write("              <h3>오호라 크루 추천</h3>\r\n");
      out.write("              <div\r\n");
      out.write("                df-banner-code=\"common-recommend\"\r\n");
      out.write("                class=\"recommend_banner_wrap swiper-wrapper df-bannermanager df-bannermanager-common-recommend\"\r\n");
      out.write("                style=\"\r\n");
      out.write("                  transition-duration: 0ms;\r\n");
      out.write("                  transform: translate3d(-260px, 0px, 0px);\r\n");
      out.write("                \"\r\n");
      out.write("              >\r\n");
      out.write("                <div\r\n");
      out.write("                  df-banner-clone=\"\"\r\n");
      out.write("                  class=\"SP_eventBn_li swiper-slide swiper-slide-prev\"\r\n");
      out.write("                >\r\n");
      out.write("                  <a\r\n");
      out.write("                    href=\"#empty\"\r\n");
      out.write("                    ><div class=\"imgBox\">\r\n");
      out.write("                      <img\r\n");
      out.write("                        src=\"https://ohora.kr/web/upload/appfiles/ZaReJam3QiELznoZeGGkMG/94fad6d6474acf635b9c771591480a7c.png\"\r\n");
      out.write("                        alt=\"페이코 상시 12% 할인\"\r\n");
      out.write("                      />\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"txtBox\">페이코 상시 12% 할인</div></a\r\n");
      out.write("                  >\r\n");
      out.write("                </div>\r\n");
      out.write("                <div\r\n");
      out.write("                  df-banner-clone=\"\"\r\n");
      out.write("                  class=\"SP_eventBn_li swiper-slide swiper-slide-active\"\r\n");
      out.write("                >\r\n");
      out.write("                  <a href=\"#empty\"\r\n");
      out.write("                    ><div class=\"imgBox\">\r\n");
      out.write("                      <img\r\n");
      out.write("                        src=\"	https://ohora.kr/web/upload/appfiles/ZaReJam3QiELznoZeGGkMG/4cd90f97beaaeddde49bbad02da10bc5.webp\"\r\n");
      out.write("                        alt=\"앱 다운 시 무료배송\"\r\n");
      out.write("                      />\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"txtBox\">앱 다운 시 무료배송</div></a\r\n");
      out.write("                  >\r\n");
      out.write("                </div>\r\n");
      out.write("                <div\r\n");
      out.write("                  df-banner-clone=\"\"\r\n");
      out.write("                  class=\"SP_eventBn_li swiper-slide swiper-slide-next\"\r\n");
      out.write("                >\r\n");
      out.write("                  <a href=\"#empty\"\r\n");
      out.write("                    ><div class=\"imgBox\">\r\n");
      out.write("                      <img\r\n");
      out.write("                        src=\"https://ohora.kr/web/upload/appfiles/ZaReJam3QiELznoZeGGkMG/0b48933209882b54093f40d23cb23246.webp\"\r\n");
      out.write("                        alt=\"신규회원 젤램프 증정\"\r\n");
      out.write("                      />\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"txtBox\">신규회원 젤램프 증정</div></a\r\n");
      out.write("                  >\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- 스와이퍼 스크롤 -->\r\n");
      out.write("              <div class=\"swiper-scrollbar\">\r\n");
      out.write("                <div\r\n");
      out.write("                  class=\"swiper-scrollbar-drag\"\r\n");
      out.write("                  style=\"\r\n");
      out.write("                    transition-duration: 0ms;\r\n");
      out.write("                    transform: translate3d(85px, 0px, 0px);\r\n");
      out.write("                    width: 85px;\r\n");
      out.write("                  \"\r\n");
      out.write("                ></div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <span\r\n");
      out.write("                class=\"swiper-notification\"\r\n");
      out.write("                aria-live=\"assertive\"\r\n");
      out.write("                aria-atomic=\"true\"\r\n");
      out.write("              ></span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--// 오호라 크루 추천-->\r\n");
      out.write("            <div class=\"third_cate\">\r\n");
      out.write("              <a href=\"https://oe9lp.channel.io/home\"><span>CS Center</span></a>\r\n");
      out.write("              <a href=\"/projectOhora/ohora/notice.jsp\"\r\n");
      out.write("                ><span>Notice</span></a\r\n");
      out.write("              >\r\n");
      out.write("              <a href=\"/projectOhora/ohora/FAQ.jsp\"><span>FAQ</span></a>\r\n");
      out.write("              <a href=\"/projectOhora/ohora/howto.jsp\">How to</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </div> <!-- sticky 적용을 위한 태그-->\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write(" \r\n");
      out.write("  <!-- 슬라이더 초기화 코드 -->\r\n");
      out.write("    <script>\r\n");
      out.write("      $(document).ready(function () {\r\n");
      out.write("        $(\".slide_banner_top\").slick({\r\n");
      out.write("          infinite: true,\r\n");
      out.write("          speed: 300,\r\n");
      out.write("          slidesToShow: 1,\r\n");
      out.write("          dots: false,\r\n");
      out.write("          arrows: false,\r\n");
      out.write("          autoplay: true,\r\n");
      out.write("          autoplaySpeed: 3000,\r\n");
      out.write("          swipe: true,\r\n");
      out.write("          pauseOnHover: false,\r\n");
      out.write("        });\r\n");
      out.write("      });\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("		$(\"#goCart\").on(\"click\", function(event){\r\n");
      out.write("			// alert(\"test\");\r\n");
      out.write("			event.preventDefault();\r\n");
      out.write("			$(\"#CartForm\").submit();\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("      $(document).ready(function() {\r\n");
      out.write("        const searchContainer = $('.hd_search_container');\r\n");
      out.write("        const cateContainer = $('.hd_cate_container');\r\n");
      out.write("\r\n");
      out.write("        searchContainer.hide();\r\n");
      out.write("        cateContainer.hide();\r\n");
      out.write("\r\n");
      out.write("        // 검색 버튼 클릭 시\r\n");
      out.write("        $('.small_icon.search_fixed_btn').on('click', function() {\r\n");
      out.write("          if (!searchContainer.is(':visible')) {\r\n");
      out.write("            cateContainer.stop(true, true).fadeOut(300, function() {\r\n");
      out.write("              searchContainer.stop(true, true).slideDown(500).animate({ opacity: 1 }, { duration: 10 });\r\n");
      out.write("              $('#keyword').focus();\r\n");
      out.write("            });\r\n");
      out.write("          } else {\r\n");
      out.write("            searchContainer.stop(true, true).slideUp(500).animate({ opacity: 0 }, { duration: 10 });\r\n");
      out.write("          }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // 더보기 버튼 클릭 시\r\n");
      out.write("        $('.SMS_menu').on('click', function() {\r\n");
      out.write("          if (!cateContainer.is(':visible')) {\r\n");
      out.write("            searchContainer.stop(true, true).fadeOut(300, function() {\r\n");
      out.write("              cateContainer.stop(true, true).slideDown(500).animate({ opacity: 1 }, { duration: 10 });\r\n");
      out.write("              $('#keyword').focus();\r\n");
      out.write("            });\r\n");
      out.write("          } else {\r\n");
      out.write("            cateContainer.stop(true, true).slideUp(500).animate({ opacity: 0 }, { duration: 10 });\r\n");
      out.write("          }\r\n");
      out.write("        });\r\n");
      out.write("      });\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div id=\"container\">\r\n");
      out.write("		<div id=\"contents\">\r\n");
      out.write("			<div id=\"SP_boardPageChk\">\r\n");
      out.write("				<div class=\"SP_layoutFix\">\r\n");
      out.write("					<div\r\n");
      out.write("						class=\"xans-element- xans-board xans-board-readpackage-8 xans-board-readpackage xans-board-8 \">\r\n");
      out.write("						<div\r\n");
      out.write("							class=\"xans-element- xans-board xans-board-title-8 xans-board-title xans-board-8 SP_subContHeader \">\r\n");
      out.write("							<h2 class=\"SP_subTitle eng_font\">how to</h2>\r\n");
      out.write("							<!-- <p class=\"SP_subTtileStxt\">사용법&팁을 안내해드리는 공간입니다.</p> -->\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("						<!-- go_top 버튼 -->\r\n");
      out.write("			            <div id=\"floating\">\r\n");
      out.write("			                <div class=\"go_top\">\r\n");
      out.write("			                    <span class=\"icon\"></span>\r\n");
      out.write("			                </div>\r\n");
      out.write("			            </div>\r\n");
      out.write("									\r\n");
      out.write("						<form id=\"BoardDelForm\" name=\"\" action=\"/exec/front/Board/del/13\"\r\n");
      out.write("							method=\"post\" target=\"_self\" enctype=\"multipart/form-data\">\r\n");
      out.write("							<input id=\"no\" name=\"no\" value=\"148230\" type=\"hidden\"> <input\r\n");
      out.write("								id=\"bulletin_no\" name=\"bulletin_no\" value=\"137825\" type=\"hidden\">\r\n");
      out.write("							<input id=\"board_no\" name=\"board_no\" value=\"13\" type=\"hidden\">\r\n");
      out.write("							<input id=\"member_id\" name=\"member_id\" value=\"ohora2019\"\r\n");
      out.write("								type=\"hidden\"> <input id=\"list_url\" name=\"list_url\"\r\n");
      out.write("								value=\"/board/gallery/list.html?board_no=13\" type=\"hidden\">\r\n");
      out.write("							<input id=\"bdf_modify_url\" name=\"bdf_modify_url\"\r\n");
      out.write("								value=\"/board/gallery/modify.html?board_act=edit&amp;no=148230&amp;board_no=13\"\r\n");
      out.write("								type=\"hidden\"> <input id=\"bdf_del_url\"\r\n");
      out.write("								name=\"bdf_del_url\" value=\"/exec/front/Board/del/13\"\r\n");
      out.write("								type=\"hidden\"> <input id=\"bdf_action_type\"\r\n");
      out.write("								name=\"bdf_action_type\" value=\"\" type=\"hidden\">\r\n");
      out.write("							<div\r\n");
      out.write("								class=\"xans-element- xans-board xans-board-read-8 xans-board-read xans-board-8 SP_subSection\">\r\n");
      out.write("								<!--\r\n");
      out.write("                    $delete_success_url = /board/gallery/list.html\r\n");
      out.write("                    $login_page_url = /member/login.html\r\n");
      out.write("                    $deny_access_url = /board/gallery/list.html\r\n");
      out.write("                -->\r\n");
      out.write("								<div class=\"ec-base-table typeWrite \">\r\n");
      out.write("									<table border=\"1\" summary=\"\"\r\n");
      out.write("										class=\"SP_tableSt01_isThAndTd type2 SP_tableBoardRead_wrap\">\r\n");
      out.write("										<caption></caption>\r\n");
      out.write("										<colgroup>\r\n");
      out.write("											<col style=\"width: 130px;\">\r\n");
      out.write("											<col style=\"width: auto;\">\r\n");
      out.write("											<col style=\"width: 130px;\">\r\n");
      out.write("											<col style=\"width: auto;\">\r\n");
      out.write("										</colgroup>\r\n");
      out.write("										<tbody>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<th scope=\"row\">제목</th>\r\n");
      out.write("												<td colspan=\"3\">스트링리무버 사용편</td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<th scope=\"row\">작성자</th>\r\n");
      out.write("												<td colspan=\"3\">ohora <span class=\"displaynone\">(ip:)</span>\r\n");
      out.write("												</td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr class=\"\">\r\n");
      out.write("												<th class=\"displaynone\">평점</th>\r\n");
      out.write("												<td class=\"displaynone\"><img\r\n");
      out.write("													src=\"//img.echosting.cafe24.com/skin/base/board/ico_point0.gif\"\r\n");
      out.write("													alt=\"0점\"></td>\r\n");
      out.write("												<th class=\"displaynone\">추천</th>\r\n");
      out.write("												<td class=\"displaynone\"><a href=\"#none\"\r\n");
      out.write("													class=\"btnNormal\"\r\n");
      out.write("													onclick=\"BOARD_READ.article_vote('/exec/front/Board/vote/13?no=148230&amp;return_url=%2Farticle%2Fhow-to%2F13%2F148230%2F&amp;3a851df6b50f7bbce67c4=b6d8671c05ca3685573606b9e5b3fbb9&amp;board_no=13');\"><img\r\n");
      out.write("														src=\"//img.echosting.cafe24.com/skin/base/common/btn_icon_recommend.gif\"\r\n");
      out.write("														alt=\"\"> 추천하기</a></td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr class=\"\">\r\n");
      out.write("												<th class=\"displaynone\">작성일</th>\r\n");
      out.write("												<td class=\"displaynone\">2021-12-15</td>\r\n");
      out.write("												<th class=\"displaynone\">조회수</th>\r\n");
      out.write("												<td class=\"displaynone\">10890</td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											<tr>\r\n");
      out.write("												<td colspan=\"4\">\r\n");
      out.write("													<div class=\"detail\">\r\n");
      out.write("														<span class=\"SP_tbDetailThumbImg\"><img\r\n");
      out.write("															src=\"//www.ohora.kr/file_data/ohora2019/2021/12/29/40d6a19bb6e10ceba0abf53eef15fe59.jpg\"\r\n");
      out.write("															boarder=\"0\" alt=\"\" style=\"max-width: 587px !important;\"><br></span>\r\n");
      out.write("														<div class=\"fr-view fr-view-article\">\r\n");
      out.write("\r\n");
      out.write("															<!-- youtube -->\r\n");
      out.write("															<div class=\"ec-ucc-media-box-62721\"\r\n");
      out.write("																style=\"position: relative; max-height: 100%; padding-bottom: 56.25%; overflow: hidden; margin-bottom: 14px;\">\r\n");
      out.write("																	<iframe src=\"https://www.youtube.com/embed/IBZu7OBM04M\" \r\n");
      out.write("																	frameborder=\"0\" style=\"border: 0px; position: absolute; top: 0px; left: 0px; width: 100%; height: 100%;\">\r\n");
      out.write("																	</iframe>\r\n");
      out.write("																</div>\r\n");
      out.write("															<!--  -->\r\n");
      out.write("															\r\n");
      out.write("															<p>\r\n");
      out.write("															    <!-- 젤네일팁 페이지 이동 -->\r\n");
      out.write("																<a\r\n");
      out.write("																	href=\"https://www.ohora.kr/product/list.html?cate_no=162&page_num=1\">\r\n");
      out.write("																	<img\r\n");
      out.write("																	src=\"/projectOhora/resources/images/howto_detail_image/howtouse_detail13.jpg\"\r\n");
      out.write("																	class=\"fr-fic fr-dib\"></a><br>\r\n");
      out.write("															</p>\r\n");
      out.write("															<p>\r\n");
      out.write("																<img\r\n");
      out.write("																	src=\"/projectOhora/resources/images/howto_detail_image/howtouse_detail14.jpg\"\r\n");
      out.write("																	class=\"fr-fic fr-dib\">\r\n");
      out.write("															</p>\r\n");
      out.write("															<p>\r\n");
      out.write("																<img\r\n");
      out.write("																	src=\"/projectOhora/resources/images/howto_detail_image/howtouse_detail15.jpg\"\r\n");
      out.write("																	class=\"fr-fic fr-dib\">\r\n");
      out.write("															</p>\r\n");
      out.write("														</div>\r\n");
      out.write("													</div>\r\n");
      out.write("												</td>\r\n");
      out.write("											</tr>\r\n");
      out.write("											\r\n");
      out.write("											<tr class=\"displaynone \">\r\n");
      out.write("												<th scope=\"row\">비밀번호</th>\r\n");
      out.write("												<td><input id=\"password\" name=\"password\" fw-filter=\"\"\r\n");
      out.write("													fw-label=\"비밀번호\" fw-msg=\"\"\r\n");
      out.write("													onkeydown=\"if (event.keyCode == 13 || event.which == 13) { return false; }\"\r\n");
      out.write("													autocomplete=\"new-password\" value=\"\" type=\"password\">\r\n");
      out.write("													<span class=\"ec-base-help txtInfo\">삭제하려면 비밀번호를\r\n");
      out.write("														입력하세요.</span>\r\n");
      out.write("														</td>\r\n");
      out.write("											</tr>\r\n");
      out.write("										</tbody>\r\n");
      out.write("									</table>\r\n");
      out.write("								</div>\r\n");
      out.write("								\r\n");
      out.write("								<!-- 버튼 -->\r\n");
      out.write("								<div class=\"SP_submitBtn_wrap SP_submitBoardBtn_wrap \">\r\n");
      out.write("									<span class=\"SP_submitBtn_left\"> <span\r\n");
      out.write("										class=\"displaynone\"> <a href=\"#none\" onclick=\"\"\r\n");
      out.write("											class=\"SP_cm_btn SP_btn_gray_bd displaynone\"></a> <a\r\n");
      out.write("											href=\"#none\" onclick=\"\"\r\n");
      out.write("											class=\"SP_cm_btn SP_btn_gray_bd displaynone\"></a> <a\r\n");
      out.write("											href=\"#none\" onclick=\"\" class=\"SP_cm_btn SP_btn_gray_bd \">스팸신고</a>\r\n");
      out.write("											<a href=\"#none\" onclick=\"\" class=\"SP_cm_btn SP_btn_gray_bd \">스팸해제</a>\r\n");
      out.write("									</span> <a href=\"/board/how-to/13/\" class=\"btnNormalFix sizeS\">목록</a>\r\n");
      out.write("									</span> <span class=\"SP_submitBtn_right\"> \r\n");
      out.write("									\r\n");
      out.write("									<!-- 어차피 관리자만 수정,삭제,작성이 가능함~ 버튼전부 동작안함 -->\r\n");
      out.write("									<!-- 클릭하면 alert : 잘못된 접근입니다. -->\r\n");
      out.write("									<a\r\n");
      out.write("										class=\"SP_cm_btn SP_btn_gray_bd displaynone\">삭제</a> \r\n");
      out.write("										\r\n");
      out.write("<!-- 										href=\"/board/gallery/modify.html?board_act=edit&amp;no=148230&amp;board_no=13\" -->\r\n");
      out.write("										<!-- 클릭하면 alert: 본인이 작성하지 않은 게시글입니다. -->\r\n");
      out.write("										<a\r\n");
      out.write("										class=\"SP_cm_btn SP_btn_gray_bd displaynone\">수정</a> \r\n");
      out.write("										\r\n");
      out.write("<!-- 										href=\"/board/gallery/reply.html\" -->\r\n");
      out.write("										<!-- alert : 관리자만 작성 가능합니다. -->\r\n");
      out.write("										<a \r\n");
      out.write("										class=\"SP_cm_btn SP_btn_gray_bd displaynone\">답변</a>\r\n");
      out.write("									</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</form>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div\r\n");
      out.write("						class=\"xans-element- xans-board xans-board-commentpackage-8 xans-board-commentpackage xans-board-8 SP_subSection\">\r\n");
      out.write("						<form id=\"commentForm\" name=\"\"\r\n");
      out.write("							action=\"/exec/front/Board/CommentUpdate/13\" method=\"post\"\r\n");
      out.write("							target=\"_self\" enctype=\"multipart/form-data\"\r\n");
      out.write("							style=\"display: none;\">\r\n");
      out.write("							<input id=\"board_no\" name=\"board_no\" value=\"13\" type=\"hidden\">\r\n");
      out.write("							<input id=\"no\" name=\"no\" value=\"148230\" type=\"hidden\"> <input\r\n");
      out.write("								id=\"comment_no\" name=\"comment_no\" value=\"\" type=\"hidden\">\r\n");
      out.write("							<input id=\"member_id\" name=\"member_id\" value=\"\" type=\"hidden\">\r\n");
      out.write("							<div\r\n");
      out.write("								class=\"xans-element- xans-board xans-board-commentform-8 xans-board-commentform xans-board-8 SP_commentModify_wrap \">\r\n");
      out.write("								<fieldset>\r\n");
      out.write("									<legend>댓글 수정</legend>\r\n");
      out.write("									<p>\r\n");
      out.write("										비밀번호 : <input id=\"comment_password\" name=\"comment_password\"\r\n");
      out.write("											fw-filter=\"isFill\" fw-label=\"댓글비밀번호\" fw-msg=\"\"\r\n");
      out.write("											autocomplete=\"new-password\" value=\"\" type=\"password\">\r\n");
      out.write("										<span class=\"secret displaynone\"><label>비밀댓글</label></span>\r\n");
      out.write("									</p>\r\n");
      out.write("									<div class=\"view\">\r\n");
      out.write("										<textarea id=\"comment_modify\" name=\"comment_modify\"\r\n");
      out.write("											fw-filter=\"isFill\" fw-label=\"댓글내용\" fw-msg=\"\"></textarea>\r\n");
      out.write("										<span class=\"submit\"> <a href=\"#none\"\r\n");
      out.write("											class=\"btnEm sizeL\"\r\n");
      out.write("											onclick=\"BOARD_COMMENT.comment_update_ok('commentForm');\">수정</a>\r\n");
      out.write("											<a href=\"#none\" class=\"btnNormal sizeL\"\r\n");
      out.write("											onclick=\"BOARD_COMMENT.comment_cancel_ok('commentForm');\">취소</a>\r\n");
      out.write("										</span>\r\n");
      out.write("									</div>\r\n");
      out.write("									<p class=\"displaynone\">/ byte</p>\r\n");
      out.write("								</fieldset>\r\n");
      out.write("							</div>\r\n");
      out.write("						</form>\r\n");
      out.write("						<form id=\"commentSecretForm\" name=\"\"\r\n");
      out.write("							action=\"/exec/front/Board/CommentSecret/13\" method=\"post\"\r\n");
      out.write("							target=\"_self\" enctype=\"multipart/form-data\"\r\n");
      out.write("							style=\"display: none;\">\r\n");
      out.write("							<input id=\"board_no\" name=\"board_no\" value=\"13\" type=\"hidden\">\r\n");
      out.write("							<input id=\"comment_no\" name=\"comment_no\" value=\"\" type=\"hidden\">\r\n");
      out.write("							<input id=\"pass_check\" name=\"pass_check\" value=\"F\" type=\"hidden\">\r\n");
      out.write("							<div\r\n");
      out.write("								class=\"xans-element- xans-board xans-board-commentformsecret-8 xans-board-commentformsecret xans-board-8 \">\r\n");
      out.write("								<p>\r\n");
      out.write("									비밀번호 : <input id=\"secure_password\" name=\"secure_password\"\r\n");
      out.write("										fw-filter=\"isFill\" fw-label=\"댓글비밀번호\" fw-msg=\"\"\r\n");
      out.write("										autocomplete=\"new-password\" value=\"\" type=\"password\">\r\n");
      out.write("									<a href=\"#none\" class=\"btnNormal\"\r\n");
      out.write("										onclick=\"BOARD_COMMENT.show_secret_comment('commentSecretForm');\">확인</a>\r\n");
      out.write("									<a href=\"#none\" class=\"btnNormal\"\r\n");
      out.write("										onclick=\"BOARD_COMMENT.hide_secret_comment_form('commentSecretForm');\">취소</a>\r\n");
      out.write("								</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</form>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div\r\n");
      out.write("						class=\"xans-element- xans-board xans-board-movement-8 xans-board-movement xans-board-8 SP_subSection board_movement_wrap\">\r\n");
      out.write("						<ul>\r\n");
      out.write("						<!-- 다음 글, 이전 글 연결링크 -->\r\n");
      out.write("							<li class=\"prev \"><span>이전글</span><a\r\n");
      out.write("								href=\"/projectOhora/ohora/howto_detail04.jsp\">젤네일팁 사용편</a></li>\r\n");
      out.write("							<li class=\"next \"><span>다음글</span><a\r\n");
      out.write("								href=\"/projectOhora/ohora/howto_detail08.jsp\">너리싱 네일 오일 사용법</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<script>\r\n");
      out.write("			 // go_top 버튼 스크립트\r\n");
      out.write("			$(document).ready(function() {\r\n");
      out.write("			    // go_top 버튼 클릭 시 상단으로 부드럽게 이동\r\n");
      out.write("			    $('.go_top').on('click', function() {\r\n");
      out.write("			        $('html, body').animate({ scrollTop: 0 }, 400);\r\n");
      out.write("			        return false;\r\n");
      out.write("			    });\r\n");
      out.write("			    \r\n");
      out.write("			    // 스크롤 이벤트에 따라 go_top 버튼 표시\r\n");
      out.write("			    $(window).scroll(function() {\r\n");
      out.write("			        if ($(this).scrollTop() > 200) {\r\n");
      out.write("			            $('#floating').fadeIn();\r\n");
      out.write("			        } else {\r\n");
      out.write("			            $('#floating').fadeOut();\r\n");
      out.write("			        }\r\n");
      out.write("			    });\r\n");
      out.write("			});\r\n");
      out.write("			</script>\r\n");
      out.write("			<script>\r\n");
      out.write("		    // 첫 번째 버튼 클릭 이벤트\r\n");
      out.write("		    $(\".SP_cm_btn.SP_btn_gray_bd.displaynone\").eq(2).on(\"click\", function() {\r\n");
      out.write("		        alert(\"잘못된 접근입니다.\");\r\n");
      out.write("		    });\r\n");
      out.write("		\r\n");
      out.write("		    // 두 번째 버튼 클릭 이벤트\r\n");
      out.write("		    $(\".SP_cm_btn.SP_btn_gray_bd.displaynone\").eq(3).on(\"click\", function(){\r\n");
      out.write("		        alert(\"본인이 작성하지 않은 게시글입니다.\");\r\n");
      out.write("		    });\r\n");
      out.write("		\r\n");
      out.write("		    // 세 번째 버튼 클릭 이벤트\r\n");
      out.write("		    $(\".SP_cm_btn.SP_btn_gray_bd.displaynone\").eq(4).on(\"click\", function(){\r\n");
      out.write("		        alert(\"관리자만 작성 가능합니다.\");\r\n");
      out.write("		    });\r\n");
      out.write("		</script>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>오호라</title>\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"http://localhost/jspPro/images/SiSt.ico\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta name=\"google\" content=\"notranslate\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/cdn-main/header.css\">\r\n");
      out.write("<script src=\"http://localhost/jspPro/resources/cdn-main/example.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write(" span.material-symbols-outlined{\r\n");
      out.write("    vertical-align: text-bottom;\r\n");
      out.write(" }  \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   \r\n");
      out.write("    <!-- 아래 필수 -->\r\n");
      out.write("    <div style=\"margin-top: 12%\"></div>\r\n");
      out.write("    <div class=\"footer\">\r\n");
      out.write("      <div class=\"chat\">\r\n");
      out.write("        <div class=\"top_left\">\r\n");
      out.write("          <span class=\"kakao_chat\">\r\n");
      out.write("            <a href=\"https://oe9lp.channel.io/home\"\r\n");
      out.write("              >1:1 문의하기</a\r\n");
      out.write("            >\r\n");
      out.write("          </span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"top_right\">\r\n");
      out.write("          <a href=\"https://www.instagram.com/ohora_official/\" target=\"_blank\">\r\n");
      out.write("            <img src=\"https://www.ohora.kr/web/upload/common/ft_insta.png\" />\r\n");
      out.write("          </a>\r\n");
      out.write("          <a href=\"https://www.facebook.com/ohora.official\" target=\"_blank\">\r\n");
      out.write("            <img src=\"https://www.ohora.kr/web/upload/common/ft_facebook.png\" />\r\n");
      out.write("          </a>\r\n");
      out.write("          <a href=\"https://pf.kakao.com/_axjYfj\" target=\"_blank\">\r\n");
      out.write("            <img src=\"https://www.ohora.kr/web/upload/common/ft_kakao.png\" />\r\n");
      out.write("          </a>\r\n");
      out.write("          <a\r\n");
      out.write("            href=\"https://www.youtube.com/channel/UCV72a2QWRpEZjZYkWjXHZWQ\"\r\n");
      out.write("            target=\"_blank\"\r\n");
      out.write("          >\r\n");
      out.write("            <img src=\"https://www.ohora.kr/web/upload/common/ft_youtube.png\" />\r\n");
      out.write("          </a>\r\n");
      out.write("          <a\r\n");
      out.write("            href=\"https://post.naver.com/my.nhn?memberNo=47439708\"\r\n");
      out.write("            target=\"_blank\"\r\n");
      out.write("          >\r\n");
      out.write("            <img src=\"https://www.ohora.kr/web/upload/common/ft_naver.png\" />\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <br />\r\n");
      out.write("      <div class=\"line\"></div>\r\n");
      out.write("      <div class=\"center_menu\">\r\n");
      out.write("        <div class=\"list\" id=\"a\">\r\n");
      out.write("          주문\r\n");
      out.write("          <div class=\"sub\" id=\"aa\">\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"/projectOhora/ohora/orderlist_log.jsp\"\r\n");
      out.write("              >주문·배송내역</a\r\n");
      out.write("            ><br /><br />\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"/projectOhora/ohora/orderlist_cancel.jsp\"\r\n");
      out.write("              >취소/교환/반품내역</a\r\n");
      out.write("            ><br /><br />\r\n");
      out.write("            <a href=\"/projectOhora/ohora/offcart.jsp\">장바구니</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"line\"></div>\r\n");
      out.write("      <div class=\"center_menu\">\r\n");
      out.write("        <div class=\"list\" id=\"b\">\r\n");
      out.write("          회원\r\n");
      out.write("          <div class=\"sub\" id=\"bb\">\r\n");
      out.write("            <a href=\"#empty\">신규 혜택</a><br /><br />\r\n");
      out.write("            <a href=\"/projectOhora/ohora/membership.jsp\">멤버십 혜택</a><br /><br />\r\n");
      out.write("            <a href=\"/projectOhora/ohora/oho_mypage.jsp\">마이페이지</a><br /><br />\r\n");
      out.write("            <a href=\"/projectOhora/ohora/coupon.jsp\">적립금·쿠폰내역</a><br /><br />\r\n");
      out.write("            <a href=\"/projectOhora/ohora/oho_memInfo.jsp\">회원정보변경</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"line\"></div>\r\n");
      out.write("      <div class=\"center_menu\">\r\n");
      out.write("        <div class=\"list\" id=\"c\">\r\n");
      out.write("          서비스\r\n");
      out.write("          <div class=\"sub\" id=\"cc\">\r\n");
      out.write("            <a href=\"/projectOhora/ohora/FAQ.jsp\">FAQ</a><br /><br />\r\n");
      out.write("            <a href=\"https://oe9lp.channel.io/home\">상담톡</a><br /><br />\r\n");
      out.write("            <a href=\"/projectOhora/ohora/howto.jsp\">사용법</a><br /><br />\r\n");
      out.write("            <a href=\"/projectOhora/ohora/notice.jsp\">공지사항</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"line\"></div>\r\n");
      out.write("      <div class=\"company\" style=\"margin-top: 10px; margin-bottom: 10px;\">\r\n");
      out.write("        <p>\r\n");
      out.write("          대표 : 유기현<br />\r\n");
      out.write("          회사 : 주식회사 글루가<br />\r\n");
      out.write("          주소 : 충남 천안시 서북구 2공단8길 45 2층 (업성동)<br />\r\n");
      out.write("          사업자등록번호 : 722-87-00061<br />\r\n");
      out.write("          통신판매업신고번호 : 2017-충남천안-1055호 사업자 정보 확인<br />\r\n");
      out.write("          개인정보처리담당자 : 유태규<br />\r\n");
      out.write("          고객센터 : 1566-0554<br />\r\n");
      out.write("          평일 09:00~18:00 (Lunch 12:30~13:30)<br />\r\n");
      out.write("          영업문의 : ohora_official@ohora.com<br />\r\n");
      out.write("          제휴 & 파트너십 문의 : ohora_partnership@ohora.com<br />\r\n");
      out.write("          글로벌 제휴 & 파트너십 문의 : Global-Business@ohora.com\r\n");
      out.write("        </p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"line\"></div>\r\n");
      out.write("      <div class=\"bottom\">\r\n");
      out.write("        <span class=\"a\"><a href=\"/projectOhora/ohora/ohora_Fend_brand4.jsp\">브랜드 소개</a></span>\r\n");
      out.write("        <span class=\"b\"><a href=\"/projectOhora/ohora/termsofservice.jsp\">이용약관</a></span>\r\n");
      out.write("        <span class=\"c\"><a href=\"/projectOhora/ohora/policy.jsp\">개인정보처리방침</a></span>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </body>\r\n");
      out.write("  <script>\r\n");
      out.write("  let sw = true;\r\n");
      out.write("  \r\n");
      out.write("  let a = document.querySelector(\"#a\");\r\n");
      out.write("  let aa = document.querySelector(\"#aa\");\r\n");
      out.write("  a.onclick = function(){\r\n");
      out.write("     if(sw){\r\n");
      out.write("        aa.style.display = \"block\";\r\n");
      out.write("     }else if(!sw){\r\n");
      out.write("        aa.style.display = \"none\";\r\n");
      out.write("     }\r\n");
      out.write("     sw = !sw;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  let b = document.querySelector(\"#b\");\r\n");
      out.write("  let bb = document.querySelector(\"#bb\");\r\n");
      out.write("  b.onclick = function(){\r\n");
      out.write("     if(sw){\r\n");
      out.write("        bb.style.display = \"block\";\r\n");
      out.write("     }else if(!sw){\r\n");
      out.write("        bb.style.display = \"none\";\r\n");
      out.write("     }\r\n");
      out.write("     sw = !sw;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  let c = document.querySelector(\"#c\");\r\n");
      out.write("  let cc = document.querySelector(\"#cc\");\r\n");
      out.write("  c.onclick = function(){\r\n");
      out.write("     if(sw){\r\n");
      out.write("        cc.style.display = \"block\";\r\n");
      out.write("     }else if(!sw){\r\n");
      out.write("        cc.style.display = \"none\";\r\n");
      out.write("     }\r\n");
      out.write("     sw = !sw;\r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
