/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2024-11-12 07:30:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ohora;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/ohora/header.jsp", Long.valueOf(1731386878239L));
    _jspx_dependants.put("/ohora/footer.jsp", Long.valueOf(1731382882687L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1730336729000L));
    _jspx_dependants.put("jar:file:/C:/Users/USER/Desktop/OhoraTest/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/projectOhora/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>오호라 팀 프로젝트</title>\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"http://localhost/jspPro/images/SiSt.ico\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta name=\"google\" content=\"notranslate\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/projectOhora/resources/cdn-main/join.css\">\r\n");
      out.write("<script src=\"http://localhost/jspPro/resources/cdn-main/example.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write(" span.material-symbols-outlined{\r\n");
      out.write("    vertical-align: text-bottom;\r\n");
      out.write(" }  \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");

Integer userId = (Integer) session.getAttribute("userId");
Integer productCount = (Integer) session.getAttribute("productCount");

// 값 확인
System.out.println("header userId : " + userId);
System.out.println("header productCount : " + productCount);

String contextPath = request.getContextPath();

   // 세션에서 로그인 상태 확인
boolean isLoggedIn = (session.getAttribute("userId") != null);

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>오호라 팀 프로젝트</title>\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"http://localhost/jspPro/images/SiSt.ico\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta name=\"google\" content=\"notranslate\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/projectOhora/resources/cdn-main/header.css\">\r\n");
      out.write("<script src=\"http://localhost/jspPro/resources/cdn-main/example.js\"></script>\r\n");
      out.write("  <link\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      type=\"text/css\"\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css\"\r\n");
      out.write("    />\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write(" span.material-symbols-outlined{\r\n");
      out.write("    vertical-align: text-bottom;\r\n");
      out.write(" }  \r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<div class=\"SP_topBanner\" style=\"display: block\">\r\n");
      out.write("      <div class=\"SP_layoutMin\">\r\n");
      out.write("        <div class=\"SP_topBn_inr\"></div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"xans-element- xans-layout xans-layout-statelogoff\">\r\n");
      out.write("          <div\r\n");
      out.write("            class=\"slide_banner_top slick-initialized slick-slider\"\r\n");
      out.write("            id=\"sltop_ban\"\r\n");
      out.write("          >\r\n");
      out.write("            <div class=\"slick-list draggable\">\r\n");
      out.write("              <div\r\n");
      out.write("                class=\"slick-track\"\r\n");
      out.write("                style=\"\r\n");
      out.write("                  opacity: 1;\r\n");
      out.write("                  width: 1200px;\r\n");
      out.write("                  transform: translate3d(0px, 0px, 0px);\r\n");
      out.write("                \"\r\n");
      out.write("              >\r\n");
      out.write("                <div\r\n");
      out.write("                  class=\"slick-slide slick-current slick-active\"\r\n");
      out.write("                  data-slick-index=\"0\"\r\n");
      out.write("                  aria-hidden=\"false\"\r\n");
      out.write("                  style=\"width: 1200px\"\r\n");
      out.write("                  tabindex=\"0\"\r\n");
      out.write("                >\r\n");
      out.write("                  <a\r\n");
      out.write("                    href=\"");
      out.print( contextPath );
      out.write("/ohora.do?event=eventnew\"\r\n");
      out.write("                    tabindex=\"0\"\r\n");
      out.write("                    style=\"display: block\"\r\n");
      out.write("                    ><img\r\n");
      out.write("                      src=\"https://ohora.kr/optimize/images/pc/common/PC_header_lamp2.webp\"\r\n");
      out.write("                      style=\"width: 100%; display: block\"\r\n");
      out.write("                  /></a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- 회원 -->\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"fix_position\" class=\"modify ham_modify\">\r\n");
      out.write("      <div id=\"SMS_fixed_wrap\" class=\"SMS_fixed_wrap\">\r\n");
      out.write("        <div class=\"SP_top_wrap\">\r\n");
      out.write("          <div class=\"layout_Top\">\r\n");
      out.write("            <div\r\n");
      out.write("              class=\"xans-element- xans-layout xans-layout-statelogoff SP_gnb_inr\"\r\n");
      out.write("            >\r\n");
      out.write("            <!-- 갱신함 / 경로는 아직 안넣음 -->\r\n");
      out.write("            ");

               if ( userId == null ) {
            
      out.write("<a href=\"");
      out.print( contextPath );
      out.write("/ohora.do?join=signup\"><span class=\"title\">회원가입</span></a>|\r\n");
      out.write("                 <a href=\"");
      out.print( contextPath );
      out.write("/ohora.do?login=gologin\" class=\"log\"><span class=\"title\">로그인</span></a>\r\n");
      out.write("            ");
      
               } else if  ( userId == 1001 ) {
            
      out.write("<a href=\"");
      out.print( contextPath );
      out.write("/admin/product.do\"><span class=\"title\">관리자페이지</span></a>|\r\n");
      out.write("                <a href=\"");
      out.print(contextPath );
      out.write("/logout/logout.do\" class=\"log\"><span class=\"title\">로그아웃</span></a>\r\n");
      out.write("            ");

               } else {
            
      out.write("<a href=\"");
      out.print( contextPath );
      out.write("/mypage/mypage.do?user_id=");
      out.print( userId );
      out.write("\"><span class=\"title\">마이페이지</span></a>|\r\n");
      out.write("                <a href=\"");
      out.print(contextPath );
      out.write("/logout/logout.do\" class=\"log\"><span class=\"title\">로그아웃</span></a>\r\n");
      out.write("              ");

               } 
            
      out.write("</div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"SMS_fixed_inner\">\r\n");
      out.write("          <div class=\"xans-element- xans-layout xans-layout-logotop fixed_logo\">\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"");
      out.print( contextPath );
      out.write("/product/main.do\"\r\n");
      out.write("              style=\"display: block; text-align: center; margin-top: 30px\"\r\n");
      out.write("            >\r\n");
      out.write("              <img\r\n");
      out.write("                src=\"https://ohora.kr/web/upload/logo/ohora_BI_logotype_w.png\"\r\n");
      out.write("               \r\n");
      out.write("              />\r\n");
      out.write("            </a>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!-- 헤더 주메뉴 -->\r\n");
      out.write("          <div class=\"gnb_menu_container\">\r\n");
      out.write("            <ul class=\"gnb_menu_wrap menu_1ul\">\r\n");
      out.write("              <li class=\"eng_font menu_1li submenu\">\r\n");
      out.write("                <a href=\"/projectOhora/product/list.do?sort=new\" style=\"color:black !important;\">new</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"eng_font menu_1li submenu\">\r\n");
      out.write("                <a href=\"/projectOhora/product/list.do?sort=sales\" style=\"color:black !important;\">best</a>\r\n");
      out.write("              </li>\r\n");
      out.write("\r\n");
      out.write("              <li class=\"eng_font\">\r\n");
      out.write("                <a href=\"/projectOhora/product/list.do\" style=\"color:black !important;\">product</a>\r\n");
      out.write("\r\n");
      out.write("                <!-- 마우스 오버 시 나오는 영역(product) -->\r\n");
      out.write("                <ul class=\"menu_2ul\">\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"/projectOhora/product/list.do?catno=1&currentPage=1\"\r\n");
      out.write("                      ><span>네일</span></a\r\n");
      out.write("                    >\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"/projectOhora/product/list.do?catno=2&currentPage=1\"\r\n");
      out.write("                      ><span>페디</span></a\r\n");
      out.write("                    >\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"/projectOhora/product/list.do?catno=1&currentPage=1\"\r\n");
      out.write("                      ><span>커스텀</span></a\r\n");
      out.write("                    >\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"/projectOhora/product/list.do?catno=3&currentPage=1\"\r\n");
      out.write("                      ><span>케어 &amp; 툴</span></a\r\n");
      out.write("                    >\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <!-- //마우스 오버 시 나오는 영역(product) -->\r\n");
      out.write("              </li>\r\n");
      out.write("\r\n");
      out.write("              <li class=\"eng_font menu_1li submenu\">\r\n");
      out.write("                <a href=\"/projectOhora/product/list.do?sort=outlet\" style=\"color:black !important;\" onclick=\"checkLogin(event)\">outlet</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"eng_font\"><a href=\"");
      out.print( contextPath );
      out.write("/ohora.do?event=event\" style=\"color:black !important;\">event</a></li>\r\n");
      out.write("              <li class=\"eng_font\">\r\n");
      out.write("                <a href=\"");
      out.print( contextPath );
      out.write("/ohora.do?howto=howto\" style=\"color:black !important;\">how to</a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- //헤더 주메뉴 -->\r\n");
      out.write("\r\n");
      out.write("          <div class=\"icon_wrap\">\r\n");
      out.write("            <div class=\"small_icon search_fixed_btn\"></div>\r\n");
      out.write("            <div\r\n");
      out.write("              class=\"xans-element- xans-layout xans-layout-orderbasketcount small_icon m_cart common_cart\"\r\n");
      out.write("            >\r\n");
      out.write("              <!-- 고정 값 0 을 어떻게 동적으로 바꾸는가 -->\r\n");
      out.write("              ");
      //  c:choose
      org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
      boolean _jspx_th_c_005fchoose_005f0_reused = false;
      try {
        _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fchoose_005f0.setParent(null);
        int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
        if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            //  c:when
            org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
            boolean _jspx_th_c_005fwhen_005f0_reused = false;
            try {
              _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
              _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
              // /ohora/header.jsp(185,13) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userId != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
              int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
              if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("<form action=\"");
                  out.print(contextPath );
                  out.write("/cart/useriscart.do\" method=\"post\" id=\"CartForm\">\r\n");
                  out.write("                     <a href=\"#\" id=\"goCart\">\r\n");
                  out.write("                         <b class=\"count EC-Layout-Basket-count\">");
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write("</b>\r\n");
                  out.write("                     </a>\r\n");
                  out.write("                 </form>\r\n");
                  out.write("             ");
                  int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
              _jspx_th_c_005fwhen_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
            }
            //  c:otherwise
            org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
            boolean _jspx_th_c_005fotherwise_005f0_reused = false;
            try {
              _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
              _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
              int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
              if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("<form action=\"");
                  out.print(contextPath );
                  out.write("/cart/nousercart.do\" method=\"post\" id=\"CartForm\">\r\n");
                  out.write("                     <a href=\"#\" id=\"goCart\">\r\n");
                  out.write("                         <b class=\"count EC-Layout-Basket-count\" >0</b>\r\n");
                  out.write("                     </a>\r\n");
                  out.write("                 </form>\r\n");
                  out.write("             ");
                  int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
              _jspx_th_c_005fotherwise_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
            }
            int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
        _jspx_th_c_005fchoose_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
      }
      out.write("</div>\r\n");
      out.write("            <div class=\"small_icon m_menu\"><a class=\"SMS_menu\"></a></div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    <!-- 검색 -->\r\n");
      out.write("    <div class=\"hd_search_container\" style=\"overflow: hidden; display: none\">\r\n");
      out.write("      <div class=\"SP_search_wrap\">\r\n");
      out.write("        <div class=\"SP_utilListSearch_inner\">\r\n");
      out.write("          <form\r\n");
      out.write("            id=\"searchBarForm\"\r\n");
      out.write("            name=\"\"\r\n");
      out.write("            action=\"/projectOhora/product/list.do\"\r\n");
      out.write("            method=\"get\"\r\n");
      out.write("            target=\"_self\"\r\n");
      out.write("            enctype=\"multipart/form-data\"\r\n");
      out.write("          >\r\n");
      out.write("            <input id=\"banner_action\" name=\"banner_action\" value=\"\" type=\"hidden\" />\r\n");
      out.write("            <div class=\"xans-element- xans-layout xans-layout-searchheader\">\r\n");
      out.write("          \r\n");
      out.write("              <fieldset>\r\n");
      out.write("                <legend style=\"display: none\">검색</legend>\r\n");
      out.write("                <input\r\n");
      out.write("                  id=\"keyword\"\r\n");
      out.write("                  name=\"keyword\"\r\n");
      out.write("                  fw-filter=\"\"\r\n");
      out.write("                  fw-label=\"검색어\"\r\n");
      out.write("                  fw-msg=\"\"\r\n");
      out.write("                  class=\"inputTypeText\"\r\n");
      out.write("                  placeholder=\"\"\r\n");
      out.write("                  onkeyup=\"SEARCH_HASHTAG.getHashtag($(this)); \"\r\n");
      out.write("                  autocomplete=\"off\"\r\n");
      out.write("                  onmousedown=\"SEARCH_BANNER.clickSearchForm(this)\"\r\n");
      out.write("                  value=\"\"\r\n");
      out.write("                  type=\"text\"\r\n");
      out.write("                /><button\r\n");
      out.write("                  type=\"button\"\r\n");
      out.write("                  class=\"SP_srh_submit_btn\"\r\n");
      out.write("                  onclick=\"SEARCH_BANNER.submitSearchBanner(this); return false;\"\r\n");
      out.write("                >\r\n");
      out.write("                  <span class=\"SP_cm_icon SP_black_search_icon\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("              </fieldset>\r\n");
      out.write("            </div>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    \r\n");
      out.write("        <!--------------- 검색 키워드 --------------->\r\n");
      out.write("        <div class=\"SP_utilListKeyword_inner\">\r\n");
      out.write("          <ul>\r\n");
      out.write("            <li><a href=\"/projectOhora/product/list.do?sort=outlet\">#OUTLET 입장하기</a></li>\r\n");
      out.write("            <li><a href=\"/projectOhora/product/list.do\">#BEST 디자인 추천</a></li>\r\n");
      out.write("            <li><a href=\"a href=\"");
      out.print( contextPath );
      out.write("/ohora.do?event=event6\">#첫구매 젤램프 증정</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--------------- 검색 키워드 --------------->\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- 더보기 -->\r\n");
      out.write("    <div class=\"hd_cate_container\" style=\"overflow: hidden; display: none\">\r\n");
      out.write("      <div class=\"SP_category_wrap\" style=\"margin-top: 172px;\">\r\n");
      out.write("        <div class=\"inner\">\r\n");
      out.write("      \r\n");
      out.write("          <div class=\"cate_wrap first\">\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("            <div class=\"big_txt\">\r\n");
      out.write("              <a class=\"eng_font big_\" href=\"/projectOhora/product/list.do?sort=new\">\r\n");
      out.write("                <span>new</span>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a class=\"\" href=\"/projectOhora/product/list.do?sort=new\">\r\n");
      out.write("                <span></span>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a class=\"\" href=\"/projectOhora/product/list.do?sort=new\">\r\n");
      out.write("                <span></span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"big_txt\" style=\"margin-top:50px\">\r\n");
      out.write("              <a class=\"eng_font big_\" href=\"/projectOhora/product/list.do?sort=sales\">\r\n");
      out.write("                <span>best</span>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a href=\"/projectOhora/product/list.do?catno=1&currentPage=1\">\r\n");
      out.write("                <span>네일</span>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a href=\"/projectOhora/product/list.do?catno=2&currentPage=1\">\r\n");
      out.write("                <span>페디</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"cate_wrap first\">\r\n");
      out.write("            <div class=\"big_txt\">\r\n");
      out.write("              <a class=\"eng_font big_\" href=\"/projectOhora/product/list.do?catno=1&currentPage=1\">\r\n");
      out.write("                <span>nail</span>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a class=\"\" href=\"/projectOhora/product/list.do?catno=1&currentPage=1\">\r\n");
      out.write("                <span>젤스트립</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"big_txt\" style=\"margin-top:80px\">\r\n");
      out.write("              <a class=\"eng_font big_\" href=\"/projectOhora/product/list.do?catno=2&currentPage=1\">\r\n");
      out.write("                <span>pedi</span>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a class=\"\" href=\"/projectOhora/product/list.do?catno=2&currentPage=1\">\r\n");
      out.write("                <span>젤스트립</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"cate_wrap first\">\r\n");
      out.write("            <div class=\"big_txt\">\r\n");
      out.write("              <a class=\"eng_font big_\" href=\"/projectOhora/product/list.do?sort=outlet\">\r\n");
      out.write("                <span>outlet</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"big_txt\">\r\n");
      out.write("              <span></span>\r\n");
      out.write("\r\n");
      out.write("              <span></span>\r\n");
      out.write("\r\n");
      out.write("              <span></span>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"big_txt\" style=\"margin-top:105px\">\r\n");
      out.write("              <a class=\"eng_font big_\" href=\"/projectOhora/product/list.do\">\r\n");
      out.write("                <span>custom</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"big_txt\" style=\"margin-top:38px\">\r\n");
      out.write("              <a class=\"eng_font big_\" href=\"/projectOhora/product/list.do?catno=3&currentPage=1\">\r\n");
      out.write("                <span>care &amp; tool</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <!--------- 첫번째 줄 메뉴(신제품 출시 관련 수정 영역) --------->\r\n");
      out.write("          <style>\r\n");
      out.write("          \r\n");
      out.write("          </style>\r\n");
      out.write("\r\n");
      out.write("          <!------- 두번째 줄 메뉴 ------>\r\n");
      out.write("          <div class=\"cate_wrap second\">\r\n");
      out.write("  \r\n");
      out.write("            <div class=\"big_txt\" style=\"margin-left: 35px; margin-bottom: 42px;\">\r\n");
      out.write("              <a class=\"big_ eng_font\" href=\"");
      out.print( contextPath );
      out.write("/ohora.do?event=event\">\r\n");
      out.write("                <span>event</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"big_txt\" style=\"margin-left: 35px;  margin-bottom: 42px;\">\r\n");
      out.write("              <a\r\n");
      out.write("                class=\"big_ eng_font\"\r\n");
      out.write("                href=\"#none\"\r\n");
      out.write("              >\r\n");
      out.write("                <span>review</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"big_txt\" style=\"margin-left: 35px;\">\r\n");
      out.write("              <a class=\"big_ eng_font\" href=\"");
      out.print( contextPath );
      out.write("/ohora.do?about=about\">\r\n");
      out.write("                <span style=\"margin-top: 10px;\">brand</span>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a class=\"\" href=\"");
      out.print( contextPath );
      out.write("/ohora.do?about=about\">\r\n");
      out.write("                <span>about</span>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a class=\"\" href=\"");
      out.print( contextPath );
      out.write("/ohora.do?membership=membership\">\r\n");
      out.write("                <span>membership</span>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a class=\"\" href=\"");
      out.print( contextPath );
      out.write("/ohora.do?magazine=magazine\">\r\n");
      out.write("                <span>magazine</span>\r\n");
      out.write("              </a>\r\n");
      out.write("              <a class=\"\" href=\"#empty\">\r\n");
      out.write("                <span>collaboration</span>\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!------ 두번째 줄 메뉴 ------>\r\n");
      out.write("          <!------ 세번째 줄 메뉴 ------>\r\n");
      out.write("          <div class=\"cate_wrap crew\">\r\n");
      out.write("  <!--오호라 크루 추천-->\r\n");
      out.write("  <div\r\n");
      out.write("    class=\"common_reco_section recommend_crew slider-container slider-container-initialized slider-container-horizontal load-complete\"\r\n");
      out.write("     style=\"margin-left: 100px\"\r\n");
      out.write("  >\r\n");
      out.write("    <h3>오호라 크루 추천</h3>\r\n");
      out.write("    <div\r\n");
      out.write("      df-banner-code=\"common-recommend\"\r\n");
      out.write("      class=\"recommend_banner_wrap slider-wrapper df-bannermanager df-bannermanager-common-recommend\"\r\n");
      out.write("      style=\"width: 260px; height: 231px\"\r\n");
      out.write("    >\r\n");
      out.write("      <div\r\n");
      out.write("        df-banner-clone=\"\"\r\n");
      out.write("        class=\"SP_eventBn_li slider-slide slider-slide-prev\"\r\n");
      out.write("      >\r\n");
      out.write("        <a href=\"#empty\"\r\n");
      out.write("          ><div class=\"imgBox\">\r\n");
      out.write("            <img\r\n");
      out.write("              src=\"https://ohora.kr/web/upload/appfiles/ZaReJam3QiELznoZeGGkMG/94fad6d6474acf635b9c771591480a7c.png\"\r\n");
      out.write("              alt=\"페이코 상시 12% 할인\"\r\n");
      out.write("            />\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"txtBox\">페이코 상시 12% 할인</div></a\r\n");
      out.write("        >\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- 스와이퍼 스크롤 -->\r\n");
      out.write("    <div class=\"slider-scrollbar\">\r\n");
      out.write("      <div\r\n");
      out.write("        class=\"slider-scrollbar-drag\"\r\n");
      out.write("        style=\"transition-duration: 0ms; transform: translate3d(0px, 0px, 0px); width: 80px;\"\r\n");
      out.write("      ></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <span\r\n");
      out.write("      class=\"slider-notification\"\r\n");
      out.write("      aria-live=\"assertive\"\r\n");
      out.write("      aria-atomic=\"true\"\r\n");
      out.write("    ></span>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!--// 오호라 크루 추천-->\r\n");
      out.write("  <div class=\"third_cate\" style=\"margin-left: 108px; margin-top: 65px;\">\r\n");
      out.write("    <a href=\"https://oe9lp.channel.io/home\"><span style=\"font-size:13px ; color:black !important;\" >CS Center &nbsp;|</span></a>\r\n");
      out.write("    <a href=\"");
      out.print( contextPath );
      out.write("/ohora.do?notice=notice\"><span style=\"font-size:13px ; color:black !important;\"> &nbsp; Notice &nbsp;|</span></a>\r\n");
      out.write("    <a href=\"");
      out.print( contextPath );
      out.write("/ohora.do?FAQ=FAQ\"><span style=\"font-size:13px ; color:black !important;\"> &nbsp; FAQ &nbsp;|</span></a>\r\n");
      out.write("    <a href=\"");
      out.print( contextPath );
      out.write("/ohora.do?howto=howto\"><span style=\"font-size:13px ; color:black !important;\"> &nbsp; How to</span></a>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("          \r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </div> <!-- sticky 적용을 위한 태그-->\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write(" \r\n");
      out.write("  <!-- 슬라이더 초기화 코드 -->\r\n");
      out.write("   <!-- 슬라이더 초기화 코드 -->\r\n");
      out.write("    <script>\r\n");
      out.write("      $(document).ready(function () {\r\n");
      out.write("        $(\".slide_banner_top\").slick({\r\n");
      out.write("          infinite: true,\r\n");
      out.write("          speed: 300,\r\n");
      out.write("          slidesToShow: 1,\r\n");
      out.write("          dots: false,\r\n");
      out.write("          arrows: false,\r\n");
      out.write("          autoplay: true,\r\n");
      out.write("          autoplaySpeed: 3000,\r\n");
      out.write("          swipe: true,\r\n");
      out.write("          pauseOnHover: false,\r\n");
      out.write("        });\r\n");
      out.write("      });\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("      $(\"#goCart\").on(\"click\", function(event){\r\n");
      out.write("         // alert(\"test\");\r\n");
      out.write("         event.preventDefault();\r\n");
      out.write("         $(\"#CartForm\").submit();\r\n");
      out.write("      });\r\n");
      out.write("   </script>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("      $(document).ready(function() {\r\n");
      out.write("        const searchContainer = $('.hd_search_container');\r\n");
      out.write("        const cateContainer = $('.hd_cate_container');\r\n");
      out.write("\r\n");
      out.write("        searchContainer.hide();\r\n");
      out.write("        cateContainer.hide();\r\n");
      out.write("\r\n");
      out.write("        // 검색 버튼 클릭 시\r\n");
      out.write("        $('.small_icon.search_fixed_btn').on('click', function() {\r\n");
      out.write("          if (!searchContainer.is(':visible')) {\r\n");
      out.write("            cateContainer.stop(true, true).fadeOut(300, function() {\r\n");
      out.write("              searchContainer.stop(true, true).slideDown(500).animate({ opacity: 1 }, { duration: 10 });\r\n");
      out.write("              $('#keyword').focus();\r\n");
      out.write("            });\r\n");
      out.write("          } else {\r\n");
      out.write("            searchContainer.stop(true, true).slideUp(500).animate({ opacity: 0 }, { duration: 10 });\r\n");
      out.write("          }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // 더보기 버튼 클릭 시\r\n");
      out.write("        $('.SMS_menu').on('click', function() {\r\n");
      out.write("          if (!cateContainer.is(':visible')) {\r\n");
      out.write("            searchContainer.stop(true, true).fadeOut(300, function() {\r\n");
      out.write("              cateContainer.stop(true, true).slideDown(500).animate({ opacity: 1 }, { duration: 10 });\r\n");
      out.write("              $('#keyword').focus();\r\n");
      out.write("            });\r\n");
      out.write("          } else {\r\n");
      out.write("            cateContainer.stop(true, true).slideUp(500).animate({ opacity: 0 }, { duration: 10 });\r\n");
      out.write("          }\r\n");
      out.write("        });\r\n");
      out.write("      });\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("     <script>\r\n");
      out.write("      function checkLogin(event) {\r\n");
      out.write("          // 로그인 여부 확인\r\n");
      out.write("          if (!isLoggedIn) {\r\n");
      out.write("              // 로그인되지 않은 경우 경고창 표시 및 링크 이동 막기\r\n");
      out.write("              event.preventDefault(); // 기본 링크 이동 동작 취소\r\n");
      out.write("              alert(\"회원만 접근 가능합니다.\");\r\n");
      out.write("          }\r\n");
      out.write("          // 로그인된 경우 링크 이동 (기본 동작)\r\n");
      out.write("      }\r\n");
      out.write("   </script>\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    // JavaScript 변수에 로그인 상태 전달\r\n");
      out.write("    var isLoggedIn = ");
      out.print( isLoggedIn );
      out.write(";\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("<script>\r\n");
      out.write("//비회원 전용 장바구니 카운트 관리자\r\n");
      out.write("const NonMemberCartManager = {\r\n");
      out.write("    lastCookieValue: null,\r\n");
      out.write("\r\n");
      out.write("    // 쿠키값 가져오기\r\n");
      out.write("    getBasketCookie() {\r\n");
      out.write("        const cookie = document.cookie\r\n");
      out.write("            .split('; ')\r\n");
      out.write("            .find(row => row.startsWith('basketItems='));\r\n");
      out.write("        return cookie ? cookie.split('=')[1] : null;\r\n");
      out.write("    },\r\n");
      out.write("\r\n");
      out.write("    // 카운트 업데이트\r\n");
      out.write("    updateCount() {\r\n");
      out.write("        try {\r\n");
      out.write("            const cookieValue = this.getBasketCookie();\r\n");
      out.write("            if (cookieValue) {\r\n");
      out.write("                const basketItems = JSON.parse(decodeURIComponent(cookieValue));\r\n");
      out.write("                if (Array.isArray(basketItems)) {\r\n");
      out.write("                    const countElement = document.querySelector('.EC-Layout-Basket-count');\r\n");
      out.write("                    if (countElement) {\r\n");
      out.write("                        countElement.textContent = basketItems.length;\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        } catch (error) {\r\n");
      out.write("            console.error('장바구니 쿠키 처리 오류:', error);\r\n");
      out.write("        }\r\n");
      out.write("    },\r\n");
      out.write("\r\n");
      out.write("    // 쿠키 변경 확인 및 업데이트\r\n");
      out.write("    checkAndUpdate() {\r\n");
      out.write("        const currentCookie = this.getBasketCookie();\r\n");
      out.write("        if (currentCookie !== this.lastCookieValue) {\r\n");
      out.write("            this.lastCookieValue = currentCookie;\r\n");
      out.write("            this.updateCount();\r\n");
      out.write("        }\r\n");
      out.write("    },\r\n");
      out.write("\r\n");
      out.write("    // 모니터링 시작\r\n");
      out.write("    startMonitoring() {\r\n");
      out.write("        // 초기값 설정\r\n");
      out.write("        this.lastCookieValue = this.getBasketCookie();\r\n");
      out.write("        this.updateCount();\r\n");
      out.write("\r\n");
      out.write("        // 주기적으로 쿠키 변경 확인\r\n");
      out.write("        setInterval(() => {\r\n");
      out.write("            this.checkAndUpdate();\r\n");
      out.write("        }, 100);\r\n");
      out.write("    }\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("// 페이지 로드 시 비회원인 경우에만 모니터링 시작\r\n");
      out.write("document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("    const userId = \"");
      out.print( userId );
      out.write("\";\r\n");
      out.write("    \r\n");
      out.write("    // 비회원일 때만 쿠키 기반 카운트 모니터링 실행\r\n");
      out.write("    if (userId === \"null\" || userId === \"\") {\r\n");
      out.write("        NonMemberCartManager.startMonitoring();\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("// 장바구니 담기 버튼 클릭 시 비회원인 경우에만 즉시 업데이트 트리거\r\n");
      out.write("document.querySelector('.SP_cartBtn')?.addEventListener('click', function() {\r\n");
      out.write("    const userId = \"");
      out.print( userId );
      out.write("\";\r\n");
      out.write("    if (userId === \"null\" || userId === \"\") {\r\n");
      out.write("        setTimeout(() => {\r\n");
      out.write("            NonMemberCartManager.checkAndUpdate();\r\n");
      out.write("        }, 100);\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div id=\"wrap\" style=\"padding-top: 156px !important;\">\r\n");
      out.write("            <div id=\"container\">\r\n");
      out.write("                <div id=\"contents\">\r\n");
      out.write("                    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"SMS_marketingCustom\">\r\n");
      out.write("    <div class=\"SP_joinIntroContainer SP_layoutFix\">\r\n");
      out.write("        <div class=\"SP_joinIntroinner\">\r\n");
      out.write("            <!--div class=\"SP_joinIntro_Top\">\r\n");
      out.write("            <div module=\"bannermanage2_display_16\" class=\"login_bnr_zone\">\r\n");
      out.write("            <a href=\"{$href}\" alt=\"{$title}\" {$target} >{$banner}</a>\r\n");
      out.write("            </div>		\r\n");
      out.write("            </div-->\r\n");
      out.write("            <div id=\"SMS_join_intro\">\r\n");
      out.write("                <!--div df-banner-code=\"join-banner\" hidden class=\"SP_joinIntro_Top\">\r\n");
      out.write("                <div df-banner-clone class=\"login_bnr_zone\">\r\n");
      out.write("                <a href=\"{#href}\">{#item}</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                </div-->	\r\n");
      out.write("                <div class=\"join_title\">\r\n");
      out.write("                    카카오 간편 회원가입 시<br><b>무료배송과 3,000원 할인 쿠폰</b>을<br> 선물로 드려요.\r\n");
      out.write("                </div>	\r\n");
      out.write("                <div class=\"coupon_img\"></div>\r\n");
      out.write("               \r\n");
      out.write("                <div class=\"SP_joinIntro_Cont\">\r\n");
      out.write("                    <form id=\"member_form_1708730238\" name=\"\" action=\"/exec/front/Member/login/\" method=\"post\" target=\"_self\" enctype=\"multipart/form-data\">\r\n");
      out.write("						<input id=\"returnUrl\" name=\"returnUrl\" value=\"https://www.ohora.kr/\" type=\"hidden\">\r\n");
      out.write("						<input id=\"forbidIpUrl\" name=\"forbidIpUrl\" value=\"/\" type=\"hidden\">\r\n");
      out.write("						<input id=\"certificationUrl\" name=\"certificationUrl\" value=\"/intro/adult_certification.html\" type=\"hidden\">\r\n");
      out.write("						<input id=\"sIsSnsCheckid\" name=\"sIsSnsCheckid\" value=\"\" type=\"hidden\">\r\n");
      out.write("						<input id=\"sProvider\" name=\"sProvider\" value=\"\" type=\"hidden\"><div class=\"xans-element- xans-member xans-member-login \"><div class=\"btnJoin btnArea type1\">\r\n");
      out.write("						                            <a href=\"#none\" class=\"btnKakao  sns_login_Btn\" onclick=\"MemberAction.kakaosyncLogin('9ae31018e6a3df11adb5d4dfa9cc9d37')\"><span>카카오로 <span>3</span>초 만에 시작하기</span></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("						<div class=\"displaynone\">\r\n");
      out.write("                            <a href=\"");
      out.print( contextPath );
      out.write("/ohora.do?join=signup\" class=\"SP_cm_btn type2 SP_btn_black_bg\">일반 회원가입</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("						<input id=\"returnUrl\" name=\"returnUrl\" value=\"/index.html\" type=\"hidden\">\r\n");
      out.write("						<input id=\"forbidIpUrl\" name=\"forbidIpUrl\" value=\"/\" type=\"hidden\">\r\n");
      out.write("						<input id=\"certificationUrl\" name=\"certificationUrl\" value=\"/intro/adult_certification.html\" type=\"hidden\">\r\n");
      out.write("						<input id=\"sIsSnsCheckid\" name=\"sIsSnsCheckid\" value=\"\" type=\"hidden\">\r\n");
      out.write("						<input id=\"sProvider\" name=\"sProvider\" value=\"\" type=\"hidden\"><div class=\"xans-element- xans-member xans-member-login SP_join_snsList btnArea type1 sns \"><li class=\"lg_naver\"><a href=\"#none\" class=\"btnNaver  sns_login_Btn\" onclick=\"MemberAction.snsLogin('naver', '%2Findex.html')\"><span class=\"txt\"><strong>네이버</strong> 간편가입</span></a></li>\r\n");
      out.write("						<li class=\"normal_join\"><a href=\"/member/join.html\" class=\"SP_cm_btn SMSjoin_btnTD sns_login_Btn\"><span class=\"txt\">일반 회원가입</span></a></li>\r\n");
      out.write("						<li class=\"lg_apple\"><a href=\"#none\" class=\"btnApple  sns_login_Btn\" onclick=\"MemberAction.snsLogin('apple', '%2Findex.html')\"><span>Apple로 로그인</span></a></li>\r\n");
      out.write("						<!--li class=\"lg_kakao\"><a href=\"#none\" class=\" sns_login_Btn\" onclick=\"MemberAction.kakaosyncLogin('9ae31018e6a3df11adb5d4dfa9cc9d37')\"><span class=\"txt\"><strong>카카오</strong> 간편가입</span></a></li>\r\n");
      out.write("						                            <li class=\"lg_facebook\"><a href=\"#none\" class=\" sns_login_Btn\" onclick=\"MemberAction.snsLogin('facebook', '%2Findex.html')\"><span class=\"txt\"><strong>페이스북</strong> 간편가입</span></a></li-->\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"SP_utility_Wrap\">\r\n");
      out.write("                            <div class=\"SP_findinfo\">\r\n");
      out.write("                                <li><a href=\"");
      out.print( contextPath );
      out.write("/ohora.do?login=gologin\">기존회원 로그인</a></li>\r\n");
      out.write("                                <li><a href=\"#none\">비회원 주문조회</a></li>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("					</div></form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--\r\n");
      out.write("            <div class=\"SP_joinIntro_Bottom\">\r\n");
      out.write("            <div module=\"bannermanage2_display_17\" class=\"login_bnr_zone\">\r\n");
      out.write("            <a href=\"{$href}\" alt=\"{$title}\" {$target} >{$banner}</a>\r\n");
      out.write("            </div>				\r\n");
      out.write("            </div>\r\n");
      out.write("            -->\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>오호라 팀 프로젝트</title>\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"http://localhost/jspPro/images/SiSt.ico\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<meta name=\"google\" content=\"notranslate\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/projectOhora/resources/cdn-main/header.css\">\r\n");
      out.write("<script src=\"http://localhost/jspPro/resources/cdn-main/example.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write(" span.material-symbols-outlined{\r\n");
      out.write("    vertical-align: text-bottom;\r\n");
      out.write(" }  \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   \r\n");
      out.write("    <!-- 아래 필수 -->\r\n");
      out.write("    <div style=\"margin-top: 12%\"></div>\r\n");
      out.write("    <div class=\"footer\">\r\n");
      out.write("      <div class=\"chat\">\r\n");
      out.write("        <div class=\"top_left\">\r\n");
      out.write("          <span class=\"kakao_chat\">\r\n");
      out.write("            <a href=\"https://oe9lp.channel.io/home\"\r\n");
      out.write("              >1:1 문의하기</a\r\n");
      out.write("            >\r\n");
      out.write("          </span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"top_right\">\r\n");
      out.write("          <a href=\"https://www.instagram.com/ohora_official/\" target=\"_blank\">\r\n");
      out.write("            <img src=\"https://www.ohora.kr/web/upload/common/ft_insta.png\" />\r\n");
      out.write("          </a>\r\n");
      out.write("          <a href=\"https://www.facebook.com/ohora.official\" target=\"_blank\">\r\n");
      out.write("            <img src=\"https://www.ohora.kr/web/upload/common/ft_facebook.png\" />\r\n");
      out.write("          </a>\r\n");
      out.write("          <a href=\"https://pf.kakao.com/_axjYfj\" target=\"_blank\">\r\n");
      out.write("            <img src=\"https://www.ohora.kr/web/upload/common/ft_kakao.png\" />\r\n");
      out.write("          </a>\r\n");
      out.write("          <a\r\n");
      out.write("            href=\"https://www.youtube.com/channel/UCV72a2QWRpEZjZYkWjXHZWQ\"\r\n");
      out.write("            target=\"_blank\"\r\n");
      out.write("          >\r\n");
      out.write("            <img src=\"https://www.ohora.kr/web/upload/common/ft_youtube.png\" />\r\n");
      out.write("          </a>\r\n");
      out.write("          <a\r\n");
      out.write("            href=\"https://post.naver.com/my.nhn?memberNo=47439708\"\r\n");
      out.write("            target=\"_blank\"\r\n");
      out.write("          >\r\n");
      out.write("            <img src=\"https://www.ohora.kr/web/upload/common/ft_naver.png\" />\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <br />\r\n");
      out.write("      <div class=\"line\"></div>\r\n");
      out.write("      <div class=\"center_menu\">\r\n");
      out.write("        <div class=\"list\" id=\"a\">\r\n");
      out.write("          주문\r\n");
      out.write("          <div class=\"sub\" id=\"aa\">\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"/projectOhora/ohora/orderlist_log.jsp\"\r\n");
      out.write("              >주문·배송내역</a\r\n");
      out.write("            ><br /><br />\r\n");
      out.write("            <a\r\n");
      out.write("              href=\"/projectOhora/ohora/orderlist_cancel.jsp\"\r\n");
      out.write("              >취소/교환/반품내역</a\r\n");
      out.write("            ><br /><br />\r\n");
      out.write("            <a href=\"/projectOhora/ohora/offcart.jsp\">장바구니</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"line\"></div>\r\n");
      out.write("      <div class=\"center_menu\">\r\n");
      out.write("        <div class=\"list\" id=\"b\">\r\n");
      out.write("          회원\r\n");
      out.write("          <div class=\"sub\" id=\"bb\">\r\n");
      out.write("            <a href=\"#empty\">신규 혜택</a><br /><br />\r\n");
      out.write("            <a href=\"/projectOhora/ohora/membership.jsp\">멤버십 혜택</a><br /><br />\r\n");
      out.write("            <a href=\"/projectOhora/ohora/oho_mypage.jsp\">마이페이지</a><br /><br />\r\n");
      out.write("            <a href=\"/projectOhora/ohora/coupon.jsp\">적립금·쿠폰내역</a><br /><br />\r\n");
      out.write("            <a href=\"/projectOhora/ohora/oho_memInfo.jsp\">회원정보변경</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"line\"></div>\r\n");
      out.write("      <div class=\"center_menu\">\r\n");
      out.write("        <div class=\"list\" id=\"c\">\r\n");
      out.write("          서비스\r\n");
      out.write("          <div class=\"sub\" id=\"cc\">\r\n");
      out.write("            <a href=\"/projectOhora/ohora/FAQ.jsp\">FAQ</a><br /><br />\r\n");
      out.write("            <a href=\"https://oe9lp.channel.io/home\">상담톡</a><br /><br />\r\n");
      out.write("            <a href=\"/projectOhora/ohora/howto.jsp\">사용법</a><br /><br />\r\n");
      out.write("            <a href=\"/projectOhora/ohora/notice.jsp\">공지사항</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"line\"></div>\r\n");
      out.write("      <div class=\"company\" style=\"margin-top: 10px; margin-bottom: 10px;\">\r\n");
      out.write("        <p>\r\n");
      out.write("          대표 : 유기현<br />\r\n");
      out.write("          회사 : 주식회사 글루가<br />\r\n");
      out.write("          주소 : 충남 천안시 서북구 2공단8길 45 2층 (업성동)<br />\r\n");
      out.write("          사업자등록번호 : 722-87-00061<br />\r\n");
      out.write("          통신판매업신고번호 : 2017-충남천안-1055호 사업자 정보 확인<br />\r\n");
      out.write("          개인정보처리담당자 : 유태규<br />\r\n");
      out.write("          고객센터 : 1566-0554<br />\r\n");
      out.write("          평일 09:00~18:00 (Lunch 12:30~13:30)<br />\r\n");
      out.write("          영업문의 : ohora_official@ohora.com<br />\r\n");
      out.write("          제휴 & 파트너십 문의 : ohora_partnership@ohora.com<br />\r\n");
      out.write("          글로벌 제휴 & 파트너십 문의 : Global-Business@ohora.com\r\n");
      out.write("        </p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"line\"></div>\r\n");
      out.write("      <div class=\"bottom\">\r\n");
      out.write("        <span class=\"a\"><a href=\"/projectOhora/ohora/ohora_Fend_brand4.jsp\">브랜드 소개</a></span>\r\n");
      out.write("        <span class=\"b\"><a href=\"/projectOhora/ohora/termsofservice.jsp\">이용약관</a></span>\r\n");
      out.write("        <span class=\"c\"><a href=\"/projectOhora/ohora/policy.jsp\">개인정보처리방침</a></span>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </body>\r\n");
      out.write("  <script>\r\n");
      out.write("  let sw = true;\r\n");
      out.write("  \r\n");
      out.write("  let a = document.querySelector(\"#a\");\r\n");
      out.write("  let aa = document.querySelector(\"#aa\");\r\n");
      out.write("  a.onclick = function(){\r\n");
      out.write("     if(sw){\r\n");
      out.write("        aa.style.display = \"block\";\r\n");
      out.write("     }else if(!sw){\r\n");
      out.write("        aa.style.display = \"none\";\r\n");
      out.write("     }\r\n");
      out.write("     sw = !sw;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  let b = document.querySelector(\"#b\");\r\n");
      out.write("  let bb = document.querySelector(\"#bb\");\r\n");
      out.write("  b.onclick = function(){\r\n");
      out.write("     if(sw){\r\n");
      out.write("        bb.style.display = \"block\";\r\n");
      out.write("     }else if(!sw){\r\n");
      out.write("        bb.style.display = \"none\";\r\n");
      out.write("     }\r\n");
      out.write("     sw = !sw;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  let c = document.querySelector(\"#c\");\r\n");
      out.write("  let cc = document.querySelector(\"#cc\");\r\n");
      out.write("  c.onclick = function(){\r\n");
      out.write("     if(sw){\r\n");
      out.write("        cc.style.display = \"block\";\r\n");
      out.write("     }else if(!sw){\r\n");
      out.write("        cc.style.display = \"none\";\r\n");
      out.write("     }\r\n");
      out.write("     sw = !sw;\r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
